Repository netlify/cli, pull requests merged in 2020-09, with the labels that each got.

#1190 fix(docs): hide hidden command flags from docs
  scripts/generateCommandData.js
  site/package-lock.json
  site/package.json
Labels: type: bug

#1162 feat(env): add command to list/get/set/import environment variables
  README.md
  docs/README.md
  docs/commands/env.md
  docs/commands/index.md
  site/src/_app.js
  src/commands/env/get.js
  src/commands/env/import.js
  src/commands/env/index.js
  src/commands/env/list.js
  src/commands/env/set.js
  src/commands/env/unset.js
  tests/command.addons.test.js
  tests/command.env.test.js
  tests/utils/callCli.js
  tests/utils/createLiveTestSite.js
Labels: type: feature

#1195 fix(command-env): handle non existing import file on node 8
  src/commands/env/import.js
Labels: type: bug

#1196 Feat: add traffic mesh proxy flag
  src/commands/dev/index.js
  src/lib/exec-fetcher.js
  src/lib/exec-fetcher.test.js
  src/lib/settings.js
  src/utils/global-config.js
  src/utils/live-tunnel.js
  src/utils/proxy.js
  src/utils/serve-functions.js
  src/utils/traffic-mesh.js
  tests/command.dev.test.js
  tests/utils/devServer.js
Labels: type: feature

#1197 fix(command-dev): pass functions server uri to traffic mesh
  src/commands/dev/index.js
  src/utils/detect-server.js
  src/utils/traffic-mesh.js
Labels: type: bug

#1209 docs(command-functions): fix invoke example payload
  docs/commands/functions.md
  src/commands/functions/invoke.js
Labels: type: bug

#1201 fix(command-dev): prevent Docusaurus from launching browser
  src/detectors/docusaurus.js
Labels: type: bug

#1213 chore: add commit linting
  commitlint.config.js
  package-lock.json
  package.json
Labels: type: chore

#1214 chore: use standard-version to increment versions
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: chore

#1211 fix(command-dev): change autoLaunch default to true
  src/commands/dev/index.js
  tests/utils/devServer.js
Labels: type: bug

#1216 chore: cleanup site scripts
  netlify.toml
  package-lock.json
  package.json
  scripts/algolia.js
  site/package-lock.json
  site/package.json
  site/scripts/docs.js
  site/scripts/generateCommandData.js
Labels: type: chore

#1218 docs: fix path to docs files directory
  site/scripts/docs.js
  site/scripts/generateCommandData.js
Labels: type: chore

#1219 Docs: move global flags to bottom
  docs/commands/addons.md
  docs/commands/api.md
  docs/commands/build.md
  docs/commands/deploy.md
  docs/commands/dev.md
  docs/commands/env.md
  docs/commands/functions.md
  docs/commands/init.md
  docs/commands/link.md
  docs/commands/login.md
  docs/commands/sites.md
  docs/commands/status.md
  src/commands/addons/delete.js
  src/commands/addons/list.js
  src/commands/api.js
  src/commands/build/index.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/env/import.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/init.js
  src/commands/link.js
  src/commands/login.js
  src/commands/sites/config.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/sites/list.js
  src/commands/status/index.js
Labels: type: bug

#1222 chore: fix docs script in root folder
  package.json
Labels: type: chore

#1224 docs: use 'string' instead of 'option' in docs
  docs/commands/api.md
  docs/commands/build.md
  docs/commands/deploy.md
  docs/commands/dev.md
  docs/commands/functions.md
  docs/commands/init.md
  docs/commands/link.md
  docs/commands/sites.md
  site/package-lock.json
  site/package.json
  site/scripts/generateCommandData.js
Labels: type: bug

#1223 chore: fix release script
  package.json
Labels: type: chore

#1215 Feat: proxy support
  docs/commands/addons.md
  docs/commands/api.md
  docs/commands/build.md
  docs/commands/deploy.md
  docs/commands/dev.md
  docs/commands/env.md
  docs/commands/functions.md
  docs/commands/init.md
  docs/commands/link.md
  docs/commands/login.md
  docs/commands/open.md
  docs/commands/sites.md
  docs/commands/status.md
  docs/commands/unlink.md
  docs/commands/watch.md
  package-lock.json
  package.json
  src/lib/http-agent.js
  src/lib/http-agent.test.js
  src/utils/command.js
Labels: type: feature

#1228 feat(command-dev): Support Docusaurus V2
  src/detectors/docusaurus.js
Labels: type: feature

#1229 README: use Snyk badge for deps security
  README.md
Labels: type: chore

#1240 refactor: extract deploy command logic into separate functions
  src/commands/deploy.js
Labels: type: chore

#1246 Set the log location for traffic mesh explicitly.
  src/lib/settings.js
  src/utils/state-config.js
  src/utils/traffic-mesh.js
Labels: type: chore

#1247 chore: run ava tests at the end
  package.json
Labels: type: chore

#1254 Fix invalid static parameters
  src/utils/proxy.js
  tests/command.dev.test.js
Labels: type: bug

#1244 Feat: edge handlers deploy
  src/commands/deploy.js
  src/lib/api.js
  src/lib/fs.js
  src/lib/spinner.js
  src/utils/command.js
  src/utils/edge-handlers.js
  src/utils/env.js
  src/utils/gitignore.js
  tests/command.addons.test.js
  tests/command.deploy.test.js
  tests/command.env.test.js
  tests/utils/callCli.js
  tests/utils/createLiveTestSite.js
  tests/utils/siteBuilder.js
Labels: type: feature

#1266 Feat: run build command when deploying
  docs/commands/deploy.md
  src/commands/build/index.js
  src/commands/deploy.js
  src/lib/build.js
  tests/command.deploy.test.js
Labels: type: feature

#1272 fix(command-deploy): align file filtering with buildbot
  src/commands/deploy.js
  tests/command.deploy.test.js
  tests/utils/siteBuilder.js
Labels: type: bug

#1273 fix(command-dev): pass publish directory to traffic mesh agent
  src/commands/dev/index.js
  src/utils/traffic-mesh.js
  tests/command.dev.test.js
Labels: type: bug

#1274 fix(command-deploy): handle deploy error when there are no files to deploy
  package-lock.json
  package.json
  src/commands/deploy.js
  src/lib/api.js
  src/utils/edge-handlers.js
  tests/command.deploy.test.js
Labels: type: bug

#1278 chore: remove redundant await keywords
  .eslintrc.json
  site/.eslintrc.json
  src/commands/functions/create.js
  src/hooks/analytics.js
  src/utils/command.js
  src/utils/detect-server.js
  src/utils/gh-auth.js
  src/utils/live-tunnel.js
  src/utils/parse-raw-flags.test.js
  src/utils/read-repo-url.js
  src/utils/serve-functions.js
Labels: type: chore

#1280 test(command-dev): add missing test case
  tests/command.dev.test.js
Labels: type: chore

#1293 test(command-deploy): enable edge-handlers plugin test on windows
  tests/command.deploy.test.js
Labels: type: chore
