Repository netlify/cli, pull requests merged in 2020-10, with the labels that each got.

#1305 fix(command-dev): align .env and .env.development handling
  package.json
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/function-builder-detectors/netlify-lambda.js
  src/lib/fs.js
  src/utils/env.js
  src/utils/env.test.js
  tests/command.dev.test.js
Labels: type: bug

#1307 refactor(command-dev-exec): don't mutate process.env
  package-lock.json
  package.json
  src/commands/dev/exec.js
  tests/command.dev.exec.test.js
Labels: type: chore

#1309 refactor: remove open-browser code duplication
  src/commands/addons/auth.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/utils/command.js
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/open-browser.js
Labels: type: chore

#1313 feat(dev): add trace subcommand to simulate redirects
  src/commands/dev/trace.js
  src/utils/traffic-mesh.js
  tests/command.dev.trace.js
Labels: type: feature

#1314 chore: add lodash,underscore linting
  .eslintrc.json
  package-lock.json
  package.json
  site/.eslintrc.json
Labels: type: chore

#1315 Chore: add standard linting
  .eslintrc.json
  package-lock.json
  package.json
  site/.eslintrc.json
  site/scripts/docs.js
  site/scripts/generateCommandData.js
  site/src/_layout.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/list.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/commands/sites/index.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/functions-templates/js/apollo-graphql/apollo-graphql.js
  src/functions-templates/js/create-user/create-user.js
  src/functions-templates/js/fauna-graphql/fauna-graphql.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1.js
  src/functions-templates/js/graphql-gateway/graphql-gateway.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-charge/stripe-charge.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/functions-templates/js/url-shortener/get-route.js
  src/functions-templates/js/url-shortener/url-shortener.js
  src/utils/command.js
  src/utils/init/config-github.js
  src/utils/proxy.js
  src/utils/read-repo-url.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  src/utils/traffic-mesh.js
Labels: type: chore

#1328 chore: ignore major updates for update-notifier
  renovate.json5
Labels: type: chore

#1333 fix(command-deploy): pass buffer: true to build if --json or --silent
  src/lib/build.js
  tests/command.deploy.test.js
Labels: type: bug

#1336 refactor: cleanup createSiteAddon function
  src/commands/functions/create.js
  src/utils/addons.js
Labels: type: chore

#1338 fix(dev): add missing await
  src/commands/dev/trace.js
  src/utils/traffic-mesh.js
Labels: type: bug

#1341 Lint Ava test files
  .eslintrc.json
  package-lock.json
  package.json
  site/.eslintrc.json
  src/lib/exec-fetcher.test.js
  src/lib/http-agent.test.js
  src/utils/detect-server.test.js
  src/utils/headers.test.js
Labels: type: chore

#1340 Lint/format Markdown and HTML
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package-lock.json
  package.json
  site/.eslintrc.json
  tests/cra.test.js
  tests/site-cra/public/force.html
  tests/site-cra/public/index.html
  tests/site-cra/public/otherthing.html
  tests/site-cra/public/test.html
Labels: type: chore

#1342 Lint test files
  package.json
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/command.dev.trace.test.js
  tests/command.functions.test.js
  tests/cra.test.js
  tests/rules-proxy.test.js
Labels: type: chore

#1347 Prefer `Array.find()` over `Array.filter()`
  src/utils/serve-functions.js
Labels: type: chore

#1348 Use `Array.includes()` instead of `Array.indexOf`
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/lib/api.js
  src/utils/telemetry/index.js
  src/utils/telemetry/validation.js
Labels: type: chore

#1354 Use `Number.parseInt()` instead of `parseInt()`
  src/lib/http-agent.js
  tests/command.deploy.test.js
Labels: type: chore

#1353 Use `new Error()` instead of `Error()`
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/send-email/validations.js
  src/functions-templates/js/url-shortener/url-shortener.js
Labels: type: chore

#1350 Prefer `[...array]` over `Array.from(array)`
  src/utils/addons/compare.js
  src/utils/gitignore.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
Labels: type: chore

#1349 Make `Array.length` checks consistent
  site/scripts/docs.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/list.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/list.js
  src/commands/sites/list.js
  src/commands/watch.js
  src/utils/gitignore.js
  src/utils/headers.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
Labels: type: chore

#1352 Fix filenames case
  site/scripts/docs.js
  site/scripts/generate-command-data.js
  src/utils/detect-server.test.js
  src/utils/env.test.js
  src/utils/get-functions.test.js
  src/utils/headers.test.js
  src/utils/rules-proxy.test.js
  tests/command.addons.test.js
  tests/command.build.test.js
  tests/command.deploy.test.js
  tests/command.dev.exec.test.js
  tests/command.dev.test.js
  tests/command.dev.trace.test.js
  tests/command.env.test.js
  tests/command.functions.test.js
  tests/cra.test.js
  tests/rules-proxy.test.js
  tests/utils/call-cli.js
  tests/utils/cli-path.js
  tests/utils/create-live-test-site.js
  tests/utils/dev-server.js
  tests/utils/external-server.js
  tests/utils/site-builder.js
Labels: type: bug, type: chore

#1356 Use `Set.has()` instead of `Array.includes()`
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/utils/detect-server.js
  src/utils/proxy.js
Labels: type: chore

#1357 Small code simplification
  src/utils/telemetry/index.js
Labels: type: chore

#1359 Small code simplification
  src/functions-templates/js/oauth-passport/oauth-passport.js
Labels: type: chore

#1358 Small file path linting error
  src/commands/addons/config.js
Labels: type: chore

#1360 Use template strings
  src/utils/detect-server.js
  src/utils/dev.js
  src/utils/proxy.js
  src/utils/serve-functions.js
Labels: type: chore

#1362 Move a function to the top-level scope
  src/utils/serve-functions.js
Labels: type: chore

#1363 Prefer `String.slice()`
  src/lib/http-agent.js
  src/utils/command.js
  src/utils/headers.js
  src/utils/proxy.js
  tests/command.deploy.test.js
  tests/utils/create-live-test-site.js
Labels: type: chore

#1351 Name `error` variable consistently
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
  src/commands/api.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/env/import.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/init.js
  src/commands/link.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/commands/unlink.js
  src/commands/watch.js
  src/functions-templates/js/auth-fetch/auth-fetch.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js
  src/functions-templates/js/hello-world/hello-world.js
  src/functions-templates/js/node-fetch/node-fetch.js
  src/functions-templates/js/send-email/send-email.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-subscription/stripe-subscription.js
  src/index.js
  src/lib/api.js
  src/lib/exec-fetcher.js
  src/lib/http-agent.js
  src/utils/detect-server.js
  src/utils/edge-handlers.js
  src/utils/gitignore.js
  src/utils/init/config-github.js
  src/utils/link/link-by-prompt.js
  src/utils/parse-raw-flags.js
  src/utils/proxy.js
  src/utils/read-repo-url.js
  src/utils/serve-functions.js
  src/utils/state-config.js
  src/utils/traffic-mesh.js
  tests/command.deploy.test.js
  tests/utils/dev-server.js
  tests/utils/site-builder.js
Labels: type: chore

#1361 Avoid unnecessary `undefined`
  src/lib/api.js
  src/lib/http-agent.js
  tests/command.dev.trace.test.js
  tests/utils/dev-server.js
Labels: type: chore

#1355 Lint RegExps
  src/commands/functions/create.js
  src/commands/sites/create.js
  src/utils/proxy.js
  tests/utils/create-live-test-site.js
Labels: type: chore

#1364 Add `eslint-plugin-unicorn`
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  package.json
  site/.eslintrc.js
  site/.eslintrc.json
Labels: type: chore

#1344 refactor: use open-api method to manage addons
  src/commands/addons/auth.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
  src/commands/addons/list.js
  src/commands/functions/create.js
  src/utils/addons.js
  src/utils/addons/api.js
  src/utils/addons/prepare.js
  src/utils/dev.js
  tests/command.addons.test.js
Labels: type: chore

#1271 chore: remove fs-extra
  package-lock.json
  package.json
  renovate.json5
  site/fs.js
  site/package-lock.json
  site/package.json
  site/sync.js
  site/watch.js
  src/commands/functions/create.js
  src/lib/exec-fetcher.js
  src/lib/exec-fetcher.test.js
  src/lib/fs.js
  src/lib/http-agent.js
  src/utils/proxy.js
  tests/utils/site-builder.js
Labels: type: chore

#1380 chore(deps): ignore major updates for `del` and `dot-prop`
  renovate.json5
Labels: type: chore

#1383 chore: fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore

#1384 chore: cleanup format,lint scripts patterns
  .prettierignore
  package.json
Labels: type: chore

#1388 test(command-dev-trace): re-enable tests
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/lib/exec-fetcher.js
  src/utils/traffic-mesh.js
  tests/command.dev.trace.test.js
Labels: type: chore

#1387 Improve npm scripts
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
  scripts/run-on-error.js
Labels: type: chore

#1345 chore: use async fs in proxy js
  package.json
  src/utils/proxy.js
Labels: type: chore

#1390 chore: upgrade eslint
  package-lock.json
  package.json
  renovate.json5
Labels: type: chore

#1393 Improve `CONTRIBUTING.md` section about dev setup
  CONTRIBUTING.md
Labels: type: chore

#1394 Improve `CONTRIBUTING.md` first section
  CONTRIBUTING.md
Labels: type: chore

#1395 Add `array-callback-return` ESLint rule
  .eslintrc.js
  src/commands/dev/index.js
  src/commands/status/index.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/utils/addons/prompts.js
  src/utils/addons/render.js
  src/utils/proxy.js
  src/utils/traffic-mesh.js
  tests/utils/dev-server.js
Labels: type: chore

#1397 Add `multiline-comment-style` ESLint rule
  .eslintrc.js
  src/commands/deploy.js
  src/commands/watch.js
  src/detectors/create-react-app.js
  src/detectors/stencil.js
  src/detectors/utils/jsdetect.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/sanity-create/sanity-create.js
  src/functions-templates/js/sanity-groq/sanity-groq.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/utils/parse-raw-flags.js
Labels: type: chore

#1398 Add `no-else-return` ESLint rule
  .eslintrc.js
  src/commands/dev/index.js
  src/commands/functions/invoke.js
  src/functions-templates/js/fauna-crud/fauna-crud.js
  src/lib/api.js
  src/lib/exec-fetcher.js
  src/utils/chalk.js
  src/utils/command.js
  src/utils/gh-auth.js
Labels: type: chore

#1399 Add `no-var` ESLint rule
  .eslintrc.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/set-cookie/set-cookie.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/functions-templates/js/url-shortener/get-route.js
Labels: type: chore

#1402 Add `func-name-matching` ESLint rule
  .eslintrc.js
  src/utils/addons/validation.js
Labels: type: chore

#1415 Simplify a function
  src/functions-templates/js/send-email/validations.js
Labels: type: chore

#1414 Small refactoring of a function
  src/commands/functions/create.js
Labels: type: chore

#1405 Add `no-implicit-coercion` ESLint rule
  .eslintrc.js
  src/utils/init/config-manual.js
  src/utils/serve-functions.js
Labels: type: chore

#1400 Add `prefer-object-spread` ESLint rule
  .eslintrc.js
  src/commands/functions/invoke.js
  src/functions-templates/js/sanity-groq/sanity-groq.js
  src/utils/addons/compare.js
  src/utils/addons/diffs/index.js
  src/utils/command.js
  src/utils/gh-auth.js
  src/utils/headers.js
  src/utils/rules-proxy.js
  src/utils/telemetry/index.js
Labels: type: chore

#1416 Add `prefer-destructuring` ESLint rule
  .eslintrc.js
  src/commands/deploy.js
  src/commands/env/unset.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/link.js
  src/commands/sites/create.js
  src/function-builder-detectors/netlify-lambda.js
  src/functions-templates/js/fauna-crud/delete.js
  src/functions-templates/js/fauna-crud/fauna-crud.js
  src/functions-templates/js/fauna-crud/read.js
  src/functions-templates/js/fauna-crud/update.js
  src/functions-templates/js/submission-created/submission-created.js
  src/functions-templates/js/url-shortener/get-route.js
  src/lib/exec-fetcher.test.js
  src/utils/command.js
  src/utils/detect-server.js
  src/utils/init/config-github.js
  src/utils/link/link-by-prompt.js
  src/utils/proxy.js
  src/utils/telemetry/index.js
  src/utils/telemetry/validation.js
  tests/command.dev.test.js
  tests/command.env.test.js
  tests/utils/create-live-test-site.js
Labels: type: chore

#1453 Run GitHub hooks configuration in parallel
  src/utils/init/config-github.js
Labels: type: chore

#1406 Add `no-invalid-this` ESLint rule
  .eslintrc.js
  src/commands/functions/create.js
Labels: type: chore

#1423 Improve the performance of proxy rules parsing
  src/utils/rules-proxy.js
  src/utils/rules-proxy.test.js
Labels: type: chore

#1424 Improve performance of static proxy
  package-lock.json
  package.json
  renovate.json5
  src/utils/proxy.js
Labels: type: chore

#1403 Add `max-params` ESLint rule
  .eslintrc.js
  src/utils/proxy.js
Labels: type: chore

#1430 Remove some dead code related to linting
  .eslintrc.js
Labels: type: chore

#1432 Wrap Markdown
  .github/ISSUE_TEMPLATE/feature_request.md
  .prettierrc.json
  src/detectors/README.md
  src/function-builder-detectors/README.md
  src/functions-templates/js/README.md
  tests/site-cra/README.md
Labels: type: chore

#1439 Speedup ESLint and Prettier
  .eslintignore
  .gitignore
  .prettierignore
  package.json
Labels: type: chore

#1456 fix(command-dev-trace): pin traffic mesh agent version
  src/lib/exec-fetcher.js
  src/utils/traffic-mesh.js
Labels: type: bug

#1435 Add `.editorconfig`
  .editorconfig
  .prettierrc.json
Labels: type: chore

#1438 Remove some unused ESLint overrides
  .eslintrc.js
Labels: type: chore

#1408 Add `no-multi-assign` ESLint rule
  .eslintrc.js
  src/commands/dev/index.js
Labels: type: chore

#1410 Add `no-plusplus` ESLint rule
  .eslintrc.js
  tests/utils/dev-server.js
Labels: type: chore

#1431 Remove site `.eslintrc.js`
  .eslintrc.js
  site/.eslintrc.js
  site/scripts/docs.js
  site/scripts/generate-command-data.js
  site/src/_layout.js
Labels: type: chore

#1429 Add ESLint rules
  .eslintrc.js
Labels: type: chore

#1409 Add `no-negated-condition` ESLint rule
  .eslintrc.js
  src/commands/deploy.js
  src/commands/env/get.js
  src/utils/chalk.js
  src/utils/command.js
Labels: type: chore

#1413 Add `no-underscore-dangle` ESLint rule
  .eslintrc.js
  .github/workflows/main.yml
  src/commands/functions/invoke.js
  src/lib/exec-fetcher.js
Labels: type: chore

#1411 Add `no-promise-executor-return` ESLint rule
  .eslintrc.js
  tests/command.dev.test.js
  tests/utils/dev-server.js
Labels: type: chore

#1401 Add `prefer-template` ESLint rule
  .eslintrc.js
  site/src/_layout.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/functions-templates/js/fauna-graphql/fauna-graphql.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/graphql-gateway/graphql-gateway.js
  src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/functions-templates/js/url-shortener/get-route.js
  src/utils/command.js
  src/utils/detect-server.js
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/live-tunnel.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  tests/command.functions.test.js
Labels: type: chore

#1441 Add `eslint-plugin-eslint-comments`
  .eslintrc.js
  package-lock.json
  package.json
  src/utils/addons/diffs/options.js
  src/utils/dev.js
  src/utils/telemetry/request.js
Labels: type: chore

#1425 Add `no-await-in-loop` ESLint rule
  .eslintrc.js
  src/utils/detect-functions-builder.js
  tests/utils/dev-server.js
  tests/utils/site-builder.js
Labels: type: chore

#1434 Use trailing commas
  .prettierrc.json
  site/fs.js
  site/scripts/generate-command-data.js
  site/src/_layout.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/deploy.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/init.js
  src/commands/sites/create.js
  src/commands/status/index.js
  src/commands/switch.js
  src/commands/watch.js
  src/detectors/utils/jsdetect.js
  src/functions-templates/js/auth-fetch/.netlify-function-template.js
  src/functions-templates/js/create-user/.netlify-function-template.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-graphql/fauna-graphql.js
  src/functions-templates/js/oauth-passport/oauth-passport.js
  src/functions-templates/js/oauth-passport/utils/auth.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-charge/.netlify-function-template.js
  src/functions-templates/js/stripe-charge/stripe-charge.js
  src/functions-templates/js/stripe-subscription/.netlify-function-template.js
  src/functions-templates/js/token-hider/.netlify-function-template.js
  src/functions-templates/js/url-shortener/.netlify-function-template.js
  src/utils/addons/prompts.js
  src/utils/chalk.js
  src/utils/detect-server.js
  src/utils/dev.js
  src/utils/env.js
  src/utils/get-repo-data.js
  src/utils/gh-auth.js
  src/utils/headers.js
  src/utils/link/link-by-prompt.js
  src/utils/live-tunnel.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  tests/command.dev.test.js
  tests/command.env.test.js
  tests/site-cra/src/index.js
  tests/site-cra/src/serviceWorker.js
  tests/utils/site-builder.js
Labels: type: chore

#1427 Add `no-shadow` ESLint rule
  .eslintrc.js
  scripts/run-on-error.js
  site/fs.js
  site/sync.js
  src/commands/addons/delete.js
  src/commands/addons/list.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/env/import.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/init.js
  src/commands/link.js
  src/commands/login.js
  src/commands/open/index.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/sites/list.js
  src/commands/status/index.js
  src/functions-templates/js/graphql-gateway/graphql-gateway.js
  src/lib/http-agent.test.js
  src/utils/addons/prepare.js
  src/utils/addons/render.js
  src/utils/chalk.js
  src/utils/command.js
  src/utils/link/link-by-prompt.js
  src/utils/parse-raw-flags.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/utils/dev-server.js
  tests/utils/site-builder.js
Labels: type: chore

#1426 Add `no-magic-numbers` ESLint rule
  .eslintrc.js
  site/src/_layout.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/watch.js
  src/detectors/README.md
  src/detectors/angular.js
  src/detectors/brunch.js
  src/detectors/create-react-app.js
  src/detectors/docusaurus.js
  src/detectors/eleventy.js
  src/detectors/ember.js
  src/detectors/expo.js
  src/detectors/gatsby.js
  src/detectors/gridsome.js
  src/detectors/hexo.js
  src/detectors/hugo.js
  src/detectors/jekyll.js
  src/detectors/middleman.js
  src/detectors/next.js
  src/detectors/nuxt.js
  src/detectors/parcel.js
  src/detectors/phenomic.js
  src/detectors/quasar-v0.17.js
  src/detectors/quasar.js
  src/detectors/react-static.js
  src/detectors/sapper.js
  src/detectors/stencil.js
  src/detectors/svelte.js
  src/detectors/vue.js
  src/detectors/vuepress.js
  src/functions-templates/js/apollo-graphql-rest/random-user.js
  src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1.js
  src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2.js
  src/functions-templates/js/send-email/send-email.js
  src/functions-templates/js/send-email/validations.js
  src/functions-templates/js/set-cookie/set-cookie.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/index.js
  src/lib/exec-fetcher.test.js
  src/lib/http-agent.js
  src/utils/create-stream-promise.js
  src/utils/detect-server.js
  src/utils/detect-server.test.js
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/logo.js
  src/utils/proxy.js
  src/utils/serve-functions.js
  src/utils/traffic-mesh.js
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/cra.test.js
  tests/rules-proxy.test.js
  tests/utils/create-live-test-site.js
  tests/utils/dev-server.js
Labels: type: chore

#1412 Add `no-return-await` ESLint rule
  .eslintrc.js
  src/commands/deploy.js
  src/utils/gh-auth.js
  src/utils/proxy.js
Labels: type: chore

#1407 Add `no-inline-comments` ESLint rule
  .eslintrc.js
  site/src/_layout.js
  src/commands/dev/exec.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/commands/sites/index.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/detectors/create-react-app.js
  src/detectors/stencil.js
  src/detectors/utils/jsdetect.js
  src/functions-templates/js/auth-fetch/auth-fetch.js
  src/functions-templates/js/fauna-graphql/fauna-graphql.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/graphql-gateway/graphql-gateway.js
  src/functions-templates/js/identity-signup/identity-signup.js
  src/functions-templates/js/node-fetch/node-fetch.js
  src/functions-templates/js/sanity-create/sanity-create.js
  src/functions-templates/js/sanity-groq/sanity-groq.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/init/config-github.js
  src/utils/read-repo-url.js
  src/utils/telemetry/index.js
  tests/command.env.test.js
Labels: type: chore

#1433 Remove unnecessary quotes
  .eslintrc.js
  .prettierrc.json
  site/src/_app.js
  site/src/_layout.js
  src/commands/deploy.js
  src/commands/sites/create.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/submission-created/submission-created.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/lib/api.js
  src/utils/live-tunnel.js
  src/utils/proxy.js
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/cra.test.js
Labels: type: chore

#1422 Add `id-length` ESLint rule
  .eslintrc.js
  site/scripts/generate-command-data.js
  site/src/_app.js
  site/src/_layout.js
  site/sync.js
  src/commands/addons/delete.js
  src/commands/addons/list.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/sites/delete.js
  src/commands/sites/list.js
  src/commands/switch.js
  src/functions-templates/js/apollo-graphql/apollo-graphql.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-crud/create.js
  src/functions-templates/js/fauna-crud/delete.js
  src/functions-templates/js/fauna-crud/fauna-crud.js
  src/functions-templates/js/fauna-crud/read-all.js
  src/functions-templates/js/fauna-crud/read.js
  src/functions-templates/js/fauna-crud/update.js
  src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1.js
  src/functions-templates/js/send-email/send-email.js
  src/functions-templates/js/url-shortener/url-shortener.js
  src/utils/addons/prompts.js
  src/utils/command.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/detect-server.test.js
  src/utils/get-functions.test.js
  src/utils/gitignore.js
  src/utils/headers.js
  src/utils/init/config-github.js
  src/utils/link/link-by-prompt.js
  src/utils/proxy.js
  src/utils/read-repo-url.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  src/utils/state-config.js
  tests/command.dev.test.js
  tests/cra.test.js
  tests/rules-proxy.test.js
  tests/utils/site-builder.js
Labels: type: chore

#1419 Add `default-param-last` ESLint rule
  .eslintrc.js
  src/commands/functions/create.js
  src/utils/proxy.js
Labels: type: chore

#1421 Add `func-style` ESLint rule
  .eslintrc.js
  site/scripts/docs.js
  site/scripts/generate-command-data.js
  site/sync.js
  site/watch.js
  src/commands/addons/config.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/index.js
  src/commands/functions/invoke.js
  src/commands/login.js
  src/commands/watch.js
  src/detectors/utils/jsdetect.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/graphql-gateway/graphql-gateway.js
  src/functions-templates/js/oauth-passport/utils/auth.js
  src/functions-templates/js/serverless-ssr/app/index.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-subscription/stripe-subscription.js
  src/utils/addons/diffs/index.js
  src/utils/addons/prompts.js
  src/utils/addons/render.js
  src/utils/chalk.js
  src/utils/check-command-inputs.js
  src/utils/command.js
  src/utils/create-stream-promise.js
  src/utils/detect-server.js
  src/utils/dev.js
  src/utils/env.js
  src/utils/finders.js
  src/utils/get-repo-data.js
  src/utils/gh-auth.js
  src/utils/gitignore.js
  src/utils/headers.js
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/live-tunnel.js
  src/utils/open-browser.js
  src/utils/parse-raw-flags.js
  src/utils/proxy.js
  src/utils/read-repo-url.js
  src/utils/rules-proxy.js
  src/utils/serve-functions.js
  src/utils/telemetry/index.js
  src/utils/telemetry/validation.js
  tests/command.env.test.js
  tests/utils/call-cli.js
  tests/utils/create-live-test-site.js
  tests/utils/dev-server.js
Labels: type: chore

#1458 feat(command-dev-local): pass path to bundler plugin CLI to mesh forward
  package-lock.json
  package.json
  src/utils/traffic-mesh.js
Labels: type: feature

#1440 Add Codecov test coverage
  .github/workflows/main.yml
  README.md
  codecov.yml
  scripts/coverage.sh
Labels: type: chore

#1462 Use `@netlify/eslint-config-node`
  .eslintrc.js
  .prettierrc.json
  package-lock.json
  package.json
Labels: type: chore

#1470 chore(renovate): add npm constraint
  renovate.json5
Labels: type: chore

#1468 chore: fix lockfile
  package-lock.json
Labels: type: chore

#1473 fix: don't pass bundler path to mesh forward
  src/utils/traffic-mesh.js
Labels: type: bug

#1474 chore: force renovate to use npm v6
  renovate.json5
Labels: type: chore

#1472 Add `plugin:node/recommended`
  .eslintrc.js
  .github/workflows/main.yml
  netlify.toml
  package.json
  site/package-lock.json
  site/package.json
  site/src/_app.js
  site/src/_ui.js
Labels: type: chore

#1476 fix: support index.js function name
  src/utils/finders.js
Labels: type: bug

#1479 feat(command-dev): don't error when background functions don't return a response
  src/utils/get-functions.js
  src/utils/get-functions.test.js
  src/utils/serve-functions.js
  tests/command.dev.test.js
Labels: type: feature

#1483 Add `node/global-require` linting rule
  .eslintrc.js
  site/scripts/generate-command-data.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/functions-templates/js/fauna-crud/fauna-crud.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/url-shortener/url-shortener.js
  src/utils/command.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/init/config-manual.js
  tests/command.dev.test.js
Labels: type: chore

#1484 Add `node/callback-return` ESLint rule
  .eslintrc.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/send-email/send-email.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-charge/stripe-charge.js
Labels: type: chore

#1485 Upgrade `@netlify/eslint-config-node`
  .eslintrc.js
  package-lock.json
  package.json
  src/commands/functions/invoke.js
Labels: type: chore

#1488 chore(renovate): remove constraints
  renovate.json5
Labels: type: chore

#1316 chore: unhide dev:trace
  README.md
  docs/README.md
  docs/commands/dev.md
  docs/commands/index.md
  src/commands/dev/trace.js
Labels: type: chore
