Repository netlify/cli, pull requests merged in 2020-05, with the labels that each got.

#843 Netlify Dev: Add framework = "#custom" option
  .github/workflows/main.yml
  docs/netlify-dev.md
  package.json
  src/commands/dev/index.js
  src/detectors/angular.js
  src/detectors/ember.js
  src/detectors/next.js
  src/detectors/quasar.js
  src/detectors/vue.js
  src/tests/utils/cliPath.js
  src/utils/detect-server.js
  src/utils/detect-server.test.js
  src/utils/get-functions.test.js
  src/utils/headers.test.js
  tests/addons.test.js
  tests/build.test.js
  tests/context-site/netlify.toml
  tests/cra.test.js
  tests/dev.test.js
  tests/dummy-repo/index.js
  tests/dummy-site/.env
  tests/dummy-site/_headers
  tests/dummy-site/build/index.html
  tests/dummy-site/functions/env/env.js
  tests/dummy-site/functions/override-process-env/override-process-env.js
  tests/dummy-site/functions/timeout.js
  tests/dummy-site/index.html
  tests/dummy-site/netlify.toml
  tests/dummy-site/package.json
  tests/failure-site/netlify.toml
  tests/rules-proxy.test.js
  tests/site-cra/.gitignore
  tests/site-cra/README.md
  tests/site-cra/_redirects
  tests/site-cra/netlify.toml
  tests/site-cra/package.json
  tests/site-cra/public/favicon.ico
  tests/site-cra/public/force.html
  tests/site-cra/public/index.html
  tests/site-cra/public/logo192.png
  tests/site-cra/public/logo512.png
  tests/site-cra/public/manifest.json
  tests/site-cra/public/robots.txt
  tests/site-cra/public/test.html
  tests/site-cra/src/App.css
  tests/site-cra/src/App.js
  tests/site-cra/src/App.test.js
  tests/site-cra/src/index.css
  tests/site-cra/src/index.js
  tests/site-cra/src/logo.svg
  tests/site-cra/src/serviceWorker.js
  tests/site-cra/src/setupTests.js
  tests/site-cra/yarn.lock
  tests/subdir-site/netlify.toml
  tests/subdir-site/subdir/.gitkeep
  tests/success-site/netlify.toml
  tests/utils/cliPath.js
  tests/utils/exec.js
  tests/utils/index.js
  tests/wrong-config-site/netlify.toml
Labels: type: bug

#874 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: feature

#844 Allow users to unlock deployments while deploying
  package-lock.json
  package.json
  src/commands/deploy.js
Labels: type: feature

#875 GitHub Actions debug
  .github/workflows/main.yml
  tests/cra.test.js
Labels: type: chore

#878 functions:invoke: Fix config problems by adding port flag
  src/commands/functions/invoke.js
  tests/dev.test.js
Labels: type: bug

#880 Fix redirect parsing issues
  package-lock.json
  package.json
Labels: type: bug

#881 Rules proxy improvements
  src/commands/dev/index.js
  src/utils/rules-proxy.js
  src/utils/rules-proxy.test.js
  tests/dummy-site/_redirects
  tests/dummy-site/netlify.toml
  tests/rules-proxy.test.js
Labels: type: enhancement

#887 Upgrade strip-ansi-control-characters
  package-lock.json
  package.json
  src/commands/dev/index.js
Labels: type: bug

#845 Watch: Init if not linked
  src/commands/init.js
  src/commands/watch.js
Labels: type: feature

#894 Add support for .env.development file
  src/commands/dev/index.js
  src/function-builder-detectors/netlify-lambda.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/env.js
  src/utils/env.test.js
  tests/dummy-site/.env
  tests/dummy-site/.env.development
  tests/site-cra/.env
Labels: type: enhancement

#895 Add .env files support fo `netlify dev:exec`
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/function-builder-detectors/netlify-lambda.js
  src/utils/env.js
  src/utils/env.test.js
  tests/dummy-site/.env
Labels: type: bug

#885 More redirect and rewrite fixes
  package.json
  src/commands/dev/index.js
  src/utils/detect-server.js
  src/utils/rules-proxy.test.js
  src/utils/serve-functions.js
  tests/cra.test.js
  tests/dev.test.js
  tests/dummy-site/404.html
  tests/dummy-site/build/index.html
  tests/dummy-site/foo.html
  tests/dummy-site/foo/bar.html
  tests/dummy-site/functions/echo.js
  tests/dummy-site/netlify.toml
  tests/dummy-site/not-foo/index.html
  tests/dummy-site/test-404b.html
  tests/dummy-site/test-404c.html
  tests/rules-proxy.test.js
  tests/site-cra/_redirects
  tests/site-cra/functions/echo.js
  tests/site-cra/netlify.toml
  tests/site-cra/public/otherthing.html
  tests/utils/index.js
Labels: blocked, type: bug

#897 Fix netlify dev --live
  src/commands/dev/index.js
Labels: type: bug

#899 Improve error when cant connect to targetPort
  src/commands/dev/index.js
Labels: type: enhancement

#900 Internal only: Rename proxyPort to frameworkPort
  src/commands/dev/index.js
  src/detectors/README.md
  src/detectors/angular.js
  src/detectors/brunch.js
  src/detectors/create-react-app.js
  src/detectors/docusaurus.js
  src/detectors/eleventy.js
  src/detectors/ember.js
  src/detectors/expo.js
  src/detectors/gatsby.js
  src/detectors/gridsome.js
  src/detectors/hexo.js
  src/detectors/hugo.js
  src/detectors/jekyll.js
  src/detectors/middleman.js
  src/detectors/next.js
  src/detectors/nuxt.js
  src/detectors/parcel.js
  src/detectors/phenomic.js
  src/detectors/quasar-v0.17.js
  src/detectors/quasar.js
  src/detectors/react-static.js
  src/detectors/sapper.js
  src/detectors/stencil.js
  src/detectors/svelte.js
  src/detectors/vue.js
  src/detectors/vuepress.js
  src/utils/detect-server.js
  src/utils/detect-server.test.js
Labels: type: enhancement

#902 Improve Netlify Dev config and docs
  docs/netlify-dev.md
  package-lock.json
  package.json
  site/package-lock.json
  src/commands/dev/index.js
  src/utils/detect-server.js
  src/utils/detect-server.test.js
Labels: type: enhancement

#905 Dev: Dont add dots when waiting for port
  src/commands/dev/index.js
Labels: type: enhancement

#910 fix: use named Octokit import
  .github/workflows/main.yml
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  tests/addons.test.js
Labels: type: bug

#918 Improve dev and CRA tests logic
  tests/cra.test.js
  tests/dev.test.js
Labels: type: enhancement

#913 test: move CRA test app install from github action to test setup
  .github/workflows/main.yml
  tests/cra.test.js
Labels: type: chore

#917 Update Netlify Dev docs
  docs/netlify-dev.md
Labels: type: enhancement

#925 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: dependencies, type: feature

#879 docs: add build command doc for repo + cli.netlify.com
  .gitignore
  docs/commands/build.md
  site/src/_app.js
Labels: type: enhancement, type: feature

#926 Fix CI tests failing
  docs/commands/build.md
Labels: type: chore

#931 Dev: Pass query params in redirect and rewrites
  src/commands/dev/index.js
Labels: type: bug
