Repository netlify/cli, pull requests merged in 2020-07, with the labels that each got.

#973 Dev: Fix false positives for Netlify Forms
  src/commands/dev/index.js
  tests/dev.test.js
Labels: type: bug

#974 fix: wait for chokidar ready event before listening to function builder src directory
  package-lock.json
  package.json
  src/commands/dev/index.js
Labels: type: bug

#975 Use base64 encoding for binary types
  src/utils/serve-functions.js
Labels: type: enhancement

#966 Deploy: Force async on large deployments
  src/commands/deploy.js
Labels: type: enhancement

#978 fixes #977 change request body validation
  src/utils/serve-functions.js
  tests/dev.test.js
  tests/dummy-site/functions/no-body.js
Labels: type: bug

#976 Functions: Handle query parameters correctly
  src/utils/serve-functions.js
  tests/dev.test.js
Labels: type: bug

#603 Mock identity response with properly-shaped data
  src/commands/functions/invoke.js
Labels: type: feature

#983 Fix typos in docs/netlify-dev.md
  docs/netlify-dev.md
Labels: type: bug

#984 chore(deps): improve renovate config
  renovate.json
Labels: type: chore

#985 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: chore

#988 fix(function-builder): report build errors
  src/commands/dev/index.js
  src/utils/serve-functions.js
Labels: type: bug

#1008 Pass site or siteId to @netlify/config
  src/utils/command.js
Labels: type: enhancement

#1013 Remove `dependency-cruiser`
  package-lock.json
  package.json
Labels: type: chore

#1012 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: feature

#1014 Test on Node 14
  .github/workflows/main.yml
Labels: type: chore

#1016 Revert "Test on Node 14"
  .github/workflows/main.yml
Labels: type: chore

#1030 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: chore

#1033 chore(linting): update eslint to v6 and fix errors
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  scripts/generateCommandData.js
  src/commands/addons/auth.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/sites/create.js
  src/commands/status/index.js
  src/detectors/utils/jsdetect.js
  src/functions-templates/js/apollo-graphql-rest/apollo-graphql-rest.js
  src/functions-templates/js/auth-fetch/auth-fetch.js
  src/functions-templates/js/fauna-crud/create.js
  src/functions-templates/js/fauna-crud/fauna-crud.js
  src/functions-templates/js/node-fetch/node-fetch.js
  src/functions-templates/js/sanity-create/sanity-create.js
  src/functions-templates/js/sanity-groq/sanity-groq.js
  src/functions-templates/js/stripe-charge/stripe-charge.js
  src/functions-templates/js/stripe-subscription/stripe-subscription.js
  src/functions-templates/js/submission-created/submission-created.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/functions-templates/js/url-shortener/get-route.js
  src/hooks/init.js
  src/utils/addons.js
  src/utils/addons/diffs/options.js
  src/utils/addons/render.js
  src/utils/check-command-inputs.js
  src/utils/command.js
  src/utils/detect-server.js
  src/utils/dev.js
  src/utils/finders.js
  src/utils/get-repo-data.js
  src/utils/gh-auth.js
  src/utils/gitignore.js
  src/utils/headers.js
  src/utils/link/link-by-prompt.js
  src/utils/live-tunnel.js
  src/utils/read-repo-url.js
  src/utils/serve-functions.js
  src/utils/telemetry/index.js
  src/utils/telemetry/validation.js
  tests/addons.test.js
Labels: type: chore

#1037 ci(chore): auto label PRs
  .github/workflows/labeler.yml
Labels: type: chore

#1039 chore(deps): remove unused dev dependencies
  package-lock.json
  package.json
Labels: type: chore
