Repository netlify/cli, pull requests merged in 2020-11, with the labels that each got.

#1493 Add `eslint-plugin-promise`
  .eslintrc.js
Labels: type: chore

#1496 Add `eslint-plugin-import`
  .eslintrc.js
  site/scripts/generate-command-data.js
  site/src/_app.js
  src/commands/dev/trace.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/functions-templates/js/auth-fetch/auth-fetch.js
  src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js
  src/functions-templates/js/node-fetch/node-fetch.js
  src/functions-templates/js/oauth-passport/oauth-passport.js
  src/functions-templates/js/oauth-passport/utils/auth.js
  src/functions-templates/js/submission-created/submission-created.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/init/config-github.js
  src/utils/rules-proxy.js
  src/utils/rules-proxy.test.js
  src/utils/state-config.js
  src/utils/telemetry/request.js
  tests/cra.test.js
Labels: type: chore

#1504 ci: don't fail on codecov error
  scripts/coverage.sh
Labels: type: chore

#1498 Add `eslint-plugin-fp`
  .eslintrc.js
  src/utils/state-config.js
Labels: type: chore

#1505 fix: import addEnvVariables from ../../utils/dev
  src/commands/dev/exec.js
  src/commands/dev/index.js
Labels: type: bug

#1469 Install traffic-mesh via npm package
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/commands/dev/trace.js
  src/utils/traffic-mesh.js
  tests/command.dev.trace.test.js
Labels: area: command: dev, type: chore

#1513 Use new `eslint-config-node`
  package.json
  scripts/run-on-error.js
Labels: type: chore

#1515 Use new `eslint-config-node`
  .eslintrc.js
  package-lock.json
  package.json
Labels: type: chore

#1490 fix: don't override dot envs with site envs
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/utils/dev.js
  src/utils/dot-env.js
  src/utils/dot-env.test.js
  src/utils/proxy.js
  tests/command.dev.exec.test.js
Labels: type: bug

#1494 Add `promise/always-return` ESLint rule
  .eslintrc.js
  site/sync.js
  src/commands/functions/create.js
  src/functions-templates/js/fauna-graphql/sync-schema.js
  src/functions-templates/js/google-analytics/google-analytics.js
  src/functions-templates/js/google-analytics/package-lock.json
  src/functions-templates/js/google-analytics/package.json
  src/functions-templates/js/send-email/send-email.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/functions-templates/js/stripe-charge/package-lock.json
  src/functions-templates/js/stripe-charge/package.json
  src/functions-templates/js/stripe-charge/stripe-charge.js
  src/functions-templates/js/stripe-subscription/package-lock.json
  src/functions-templates/js/stripe-subscription/package.json
  src/functions-templates/js/submission-created/submission-created.js
  src/functions-templates/js/url-shortener/generate-route.js
  src/functions-templates/js/url-shortener/get-route.js
  src/functions-templates/js/url-shortener/package-lock.json
  src/functions-templates/js/url-shortener/package.json
  src/functions-templates/js/url-shortener/url-shortener.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
  src/utils/telemetry/request.js
  tests/rules-proxy.test.js
Labels: type: chore

#1520 chore(deps): pin @oclif dependencies to avoid using fs-extra v9
  package-lock.json
  package.json
Labels: type: chore

#1519 fix(build): pass team,site, addons env variables to build command
  src/commands/build/index.js
  src/commands/deploy.js
  src/lib/build.js
Labels: type: bug

#1523 Refactor functions invoke
  src/commands/functions/invoke.js
Labels: type: chore

#1478 Use `zip-it-and-ship-it` to list Functions
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/utils/finders.js
  src/utils/get-functions.js
  src/utils/get-functions.test.js
  src/utils/serve-functions.js
Labels: type: feature

#1526 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#1524 feat(dev): set path to geoip location database
  package-lock.json
  package.json
  src/commands/dev/index.js
  src/utils/traffic-mesh.js
Labels: type: feature

#1529 fix fossa pr check
  .github/workflows/fossa.yml
Labels: type: bug

#1542 Update dependency `@netlify/eslint-config-node` to `^0.6.2`
  .github/workflows/main.yml
  package-lock.json
  package.json
  scripts/coverage.sh
Labels: type: chore

#1531 docs: include npm install for site subdirectory
  CONTRIBUTING.md
Labels: type: chore

#1548 chore: update site/package-lock.json
  site/package-lock.json
Labels: type: chore

#1545 fix(command-dev): role based redirects
  package-lock.json
  package.json
  src/utils/detect-server.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
  tests/command.dev.test.js
  tests/rules-proxy.test.js
  tests/utils/site-builder.js
Labels: type: bug

#1460 Display more informative error information in TimeoutError response body
  src/utils/serve-functions.js
Labels: type: bug

#1311 fix(command-dev): allow netlify-lambda build parameters
  src/function-builder-detectors/netlify-lambda.js
  src/function-builder-detectors/tests/netlify-lambda.test.js
Labels: type: bug

#1552 test: don't run edge handlers deploy if the account doesn't support it
  tests/command.addons.test.js
  tests/command.deploy.test.js
  tests/command.env.test.js
  tests/utils/create-live-test-site.js
Labels: type: chore

#1554 fix(command-dev): warn when background functions are not supported
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/functions/create.js
  src/lib/account.js
  src/lib/build.js
  src/utils/command.js
  src/utils/dev.js
  src/utils/serve-functions.js
  tests/command.deploy.test.js
  tests/command.dev.test.js
Labels: type: bug

#1551 Stop using lodash standalone packages
  package-lock.json
  package.json
  src/commands/deploy.js
  src/commands/env/import.js
  src/commands/env/list.js
  src/commands/init.js
  src/commands/sites/create.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/utils/addons/compare.js
  src/utils/command.js
  src/utils/dev.js
  src/utils/get-repo-data.js
  src/utils/gh-auth.js
  src/utils/link/link-by-prompt.js
  src/utils/proxy.js
  src/utils/serve-functions.js
  tests/command.env.test.js
Labels: type: chore

#1556 fix(command:sites:delete): don't print duplicate netlify in help
  docs/commands/sites.md
  site/scripts/docs.js
  src/commands/sites/delete.js
Labels: type: bug

#1570 fix(command-deploy): print relevant log error when background functions are not supported
  src/commands/deploy.js
  src/lib/log.js
  src/utils/serve-functions.js
Labels: type: bug

#1571 chore(deps): unpin oclif versions
  package-lock.json
  package.json
Labels: type: chore

#1573 fix(docs): change port to targetPort when framework is #custom
  docs/netlify-dev.md
Labels: type: bug

#1574 fix(docs): add jwtSecret doc to dev section
  docs/netlify-dev.md
Labels: type: bug

#1461 Expose bundling status to CLI
  package-lock.json
  package.json
  src/lib/spinner.js
  src/utils/deferred.js
  src/utils/gh-auth.js
  src/utils/traffic-mesh.js
  tests/command.dev.test.js
  tests/utils/site-builder.js
Labels: low-risk, type: feature
