Repository netlify/cli, pull requests merged in 2020-12, with the labels that each got.

#1607 refactor(command-init): remove duplicate call to getSite
  src/commands/init.js
Labels: low-risk, type: chore

#1614 refactor(command-init): extract code into functions
  src/commands/init.js
Labels: low-risk, type: chore

#1619 fix(command-init): remove code duplication with `sites:create` and add error handling
  src/commands/init.js
  src/commands/sites/create.js
  src/utils/get-repo-data.js
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/init/config.js
  src/utils/init/netlify-toml-template.js
  src/utils/init/utils.js
  src/utils/link/link-by-prompt.js
Labels: type: bug

#1549 Fix: match root path to /* headers
  src/utils/headers.js
  src/utils/headers.test.js
  tests/command.dev.test.js
Labels: type: bug

#1650 test: add debug log
  tests/command.deploy.test.js
Labels: type: chore

#1673 test: add start dev server timeout
  tests/utils/dev-server.js
Labels: type: chore
