Repository netlify/cli, pull requests merged in 2020-06, with the labels that each got.

#934 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: chore

#907 Add support for branch deploys
  package-lock.json
  package.json
  src/commands/deploy.js
Labels: type: feature

#940 Fix shadowing of files when request has query params
  src/commands/dev/index.js
  tests/dev.test.js
Labels: type: bug

#944 Update Functions Docs to Include Functions Domain
  docs/netlify-dev.md
Labels: type: chore

#943 Deploy: Rename --branch to --alias
  src/commands/deploy.js
Labels: type: enhancement

#780 Add support for form submissions
  package-lock.json
  package.json
  src/commands/dev/index.js
  src/utils/serve-functions.js
  tests/dev.test.js
  tests/dummy-site/functions/submission-created.js
Labels: type: feature

#938 Fix query param and headers behavior
  src/utils/serve-functions.js
  tests/cra.test.js
Labels: type: bug

#949 Dev: Dont force redirect on internal URL's
  src/commands/dev/index.js
Labels: type: bug

#936 Fix checks for "command" and "dir" combination
  src/utils/detect-server.js
  src/utils/detect-server.test.js
Labels: type: bug

#956 Fix fossa
  .github/workflows/fossa.yml
Labels: type: bug

#957 Upgrade Netlify Build
  package-lock.json
  package.json
Labels: type: chore

#964 Add `--debug` CLI flag
  src/commands/addons/delete.js
  src/commands/addons/list.js
  src/commands/api.js
  src/commands/build/index.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/init.js
  src/commands/link.js
  src/commands/login.js
  src/commands/open/index.js
  src/commands/sites/config.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/sites/list.js
  src/commands/status/index.js
  src/utils/command.js
  tests/build.test.js
Labels: type: chore

#965 Fix requests hanging when function not found
  src/commands/dev/index.js
  src/utils/create-stream-promise.js
  src/utils/serve-functions.js
  tests/dev.test.js
Labels: type: bug

#953 Improve how the project root is resolved
  package-lock.json
  package.json
  src/utils/command.js
  src/utils/find-root/fixtures/git-project/some/sub/dir/.keep
  src/utils/find-root/fixtures/no-indicator/some/sub/dir/.keep
  src/utils/find-root/fixtures/state-folder/.netlify/.keep
  src/utils/find-root/fixtures/state-folder/some/sub/dir/.keep
  src/utils/find-root/fixtures/toml-config/netlify.toml
  src/utils/find-root/fixtures/toml-config/some/sub/dir/.keep
  src/utils/find-root/index.js
  src/utils/find-root/index.test.js
  src/utils/state-config.js
Labels: type: chore
