Repository netlify/cli, pull requests merged in 2021-04, with the labels that each got.

#1996 feat: add functions directory creation when non-existent in netlify.toml
  docs/commands/functions.md
  src/commands/functions/create.js
  tests/command.functions.test.js
  tests/command.init.test.js
  tests/utils/handle-questions.js
Labels: type: feature

#2028 feat: add support for shell completion
  README.md
  docs/README.md
  docs/commands/completion.md
  docs/commands/index.md
  package-lock.json
  package.json
  site/scripts/generate-command-data.js
  site/src/_app.js
  src/lib/help.js
Labels: type: feature

#2074 chore: only test Node.js 10 on linux
  .github/workflows/main.yml
Labels: type: chore

#2077 feat: rename default branch from master to main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/fossa.yml
  .github/workflows/main.yml
  .github/workflows/release-please.yml
  .github/workflows/verify-docs.yml
  CONTRIBUTING.md
  README.md
  codecov.yml
  docs/netlify-dev.md
  site/src/_layout.js
  src/detectors/README.md
  src/utils/init/utils.js
Labels: type: feature

#2088 chore(release-please): use GitHub app token
  .github/workflows/release-please.yml
Labels: type: chore

#2083 feat(detectors): add detector for Vite
  src/detectors/vite.js
Labels: type: feature

#2124 chore(renovate): ignore Node.js>=12 packages
  renovate.json5
Labels: type: chore

#2132 feat(command-dev): support secure https development
  docs/netlify-dev.md
  package-lock.json
  package.json
  src/utils/detect-server.js
  src/utils/proxy.js
  tests/assets/cert.pem
  tests/assets/key.pem
  tests/command.dev.test.js
Labels: type: feature

#2141 chore: automate npm publishing
  .github/workflows/release-please.yml
  CONTRIBUTING.md
Labels: type: chore

#2148 feat: use zisi function builder when using TypeScript functions
  src/function-builder-detectors/zisi.js
  tests/command.dev.test.js
Labels: type: feature

#2149 chore(release-please): fix release process
  .github/workflows/release-please.yml
Labels: type: chore

#2166 chore(release-please): add missing env variables
  .github/workflows/release-please.yml
Labels: type: chore

#2168 fix(deps): update to Node.js 10 supported versions, ignore others
  package-lock.json
  package.json
  renovate.json5
Labels: type: bug

#2150 chore: add package size benchmark
  .github/workflows/benchmark.yml
Labels: type: chore

#2171 test(command-dev): replace cra test with eleventy test
  package.json
  tests/eleventy-site/.eleventy.js
  tests/eleventy-site/.gitignore
  tests/eleventy-site/_redirects
  tests/eleventy-site/force.html
  tests/eleventy-site/functions/echo.js
  tests/eleventy-site/index.html
  tests/eleventy-site/netlify.toml
  tests/eleventy-site/otherthing.html
  tests/eleventy-site/package-lock.json
  tests/eleventy-site/package.json
  tests/eleventy-site/test.html
  tests/eleventy.test.js
  tests/site-cra/.env
  tests/site-cra/.gitignore
  tests/site-cra/README.md
  tests/site-cra/functions/echo.js
  tests/site-cra/netlify.toml
  tests/site-cra/package-lock.json
  tests/site-cra/package.json
  tests/site-cra/public/favicon.ico
  tests/site-cra/public/index.html
  tests/site-cra/public/logo192.png
  tests/site-cra/public/logo512.png
  tests/site-cra/public/manifest.json
  tests/site-cra/public/robots.txt
  tests/site-cra/src/App.css
  tests/site-cra/src/App.js
  tests/site-cra/src/App.test.js
  tests/site-cra/src/index.css
  tests/site-cra/src/index.js
  tests/site-cra/src/logo.svg
  tests/site-cra/src/serviceWorker.js
  tests/site-cra/src/setupTests.js
Labels: type: chore

#2169 feat: reuse existing tabs in `netlify dev` command
  package-lock.json
  package.json
  renovate.json5
  src/utils/open-browser.js
Labels: type: feature

#2143 feat(command-dev): watch all functions files
  src/utils/get-functions.js
  src/utils/get-functions.test.js
  src/utils/serve-functions.js
Labels: type: feature

#2188 chore(ci): switch to cms shell on windows
  .github/workflows/main.yml
Labels: type: chore

#2186 fix(command-dev): newly added functions are not recognized
  src/utils/serve-functions.js
Labels: type: bug

#2197 fix: delete the directory from which functions will be served
  src/function-builder-detectors/zisi.js
Labels: type: bug

#2204 fix(deps): pin memoize-one to 5.1.1
  package-lock.json
  package.json
Labels: type: bug

#2213 fix(deps): memoize-one cjs exports breaking changes
  package-lock.json
  package.json
  src/utils/get-global-config.js
Labels: type: bug

#2218 fix(deps): upgrading memoize-one to 5.2.1
  package-lock.json
  package.json
  src/utils/get-global-config.js
Labels: type: bug

#2224 fix(command-dev): handle undefined location
  src/utils/proxy.js
Labels: type: bug

#2240 fix(command-dev): revert usage of listFunctionsFiles
  src/utils/get-functions.js
  src/utils/get-functions.test.js
Labels: type: bug

#2249 test(command-dev): don't pass auth token to CLI
  tests/utils/dev-server.js
Labels: type: chore

#2235 chore(deps): ignore major updates for to-readable-stream
  renovate.json5
Labels: type: chore

#2248 feat: add npm shrinkwrap
  npm-shrinkwrap.json
  package.json
Labels: type: feature

#2251 feat(docs): recommend local install on CI
  README.md
  docs/README.md
  docs/getting-started.md
Labels: needs docs, type: feature

#2259 fix(command-dev): Update detect-server.js
  src/utils/detect-server.js
Labels: type: bug

#2263 chore: release 3.23.1
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: autorelease: pending, type: chore

#2239 fix(command-dev): use custom functions timeout if present
  src/commands/dev/index.js
  src/utils/dev.js
  src/utils/serve-functions.js
  tests/command.dev.test.js
  tests/utils/dev-server.js
Labels: type: bug

#2268 refactor(command-dev): move ms conversion closer to lambda invocation
  src/utils/dev.js
  src/utils/serve-functions.js
Labels: type: chore

#2258 feat: memoize build function
  src/function-builder-detectors/netlify-lambda.js
  src/function-builder-detectors/zisi.js
  src/utils/serve-functions.js
  tests/serving-functions.test.js
Labels: type: feature
