Repository netlify/cli, pull requests merged in 2021-01, with the labels that each got.

#1675 refactor(command-functions-invoke): use async/await
  src/commands/functions/invoke.js
Labels: type: chore

#1674 feat: add warning message if running Node.js < 10
  package.json
  src/commands/api.js
  src/utils/command.js
Labels: type: feature

#1689 chore(deps): ignore major updates for boxen
  renovate.json5
Labels: type: chore

#1694 test(command-dev): log dev server output on timeout
  package.json
  renovate.json5
  tests/utils/dev-server.js
Labels: type: chore

#1697 Fix dependency error in docs site
  site/package-lock.json
  site/package.json
Labels: type: bug, type: chore

#1700 chore: remove netlify package rules
  renovate.json5
Labels: type: chore

#1698 Add logging for ignored env vars
  src/utils/dev.js
Labels: type: feature

#1702 Document: 37 character limit on alias flag
  docs/commands/deploy.md
  src/commands/deploy.js
Labels: type: bug

#1664 feat!: drop Node.js 8 support
  .github/workflows/main.yml
  README.md
  package.json
  renovate.json5
Labels: needs docs, type: feature

#1685 Set CONTEXT when running Netlify Dev
  src/utils/dev.js
Labels: type: feature

#1713 test(command-dev): limit concurrency
  tests/command.dev.test.js
Labels: type: chore

#1727 test: add CLI timeout
  tests/utils/call-cli.js
Labels: type: chore

#1733 test: use got instead of node-fetch
  package-lock.json
  package.json
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/cra.test.js
  tests/rules-proxy.test.js
  tests/utils/got.js
Labels: type: chore

#1722 Use environment variables from @netlify/config
  package-lock.json
  package.json
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/env/get.js
  src/commands/env/list.js
  src/commands/functions/create.js
  src/lib/build.js
  src/utils/command.js
  src/utils/dev.js
  src/utils/dot-env.js
  src/utils/dot-env.test.js
  tests/command.build.test.js
  tests/command.dev.test.js
Labels: type: feature

#1742 chore(dev): update TM agent and tests
  package-lock.json
  package.json
  src/commands/dev/index.js
  src/utils/traffic-mesh.js
  tests/command.dev.test.js
Labels: type: bug

#1731 chore: update the CONTRIBUTING file with a mention to our integrationt tests
  CONTRIBUTING.md
Labels: type: chore

#1749 fix: override CONTEXT env variable
  src/utils/dev.js
  tests/command.dev.test.js
Labels: type: bug

#1747 chore: update PR labeler
  .github/workflows/labeler.yml
Labels: type: chore

#1745 chore: verify docs using a GitHub action
  .github/workflows/verify-docs.yml
  CONTRIBUTING.md
Labels: type: chore

#1746 chore: add release please
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: chore

#1748 test(http-agent): fix flaky test
  src/lib/http-agent.test.js
Labels: type: chore

#1752 feat: warn when project has netlify dir
  package.json
  src/lib/deprecations.js
  src/utils/command.js
  tests/command.test.js
Labels: type: feature

#1756 test: generate only json coverage file in CI
  package.json
Labels: type: chore

#1732 fix: wait for live session to be ready before starting tunnel
  src/utils/live-tunnel.js
Labels: type: bug

#1765 Compute slug for site name suggestions when user does not have one
  package-lock.json
  package.json
  src/commands/sites/create.js
Labels: type: bug

#1768 test(command-build): don't run on forked repos
  tests/command.build.test.js
Labels: type: chore

#1758 Fix links to api docs in `netlify api --list`
  src/commands/api.js
Labels: type: bug

#1774 fix: remove redundant Node.js 10 warning
  package.json
  src/lib/deprecations.js
  src/utils/command.js
Labels: type: bug

#1725 feat: global config sepc
  package-lock.json
  package.json
  src/commands/build/index.js
  src/commands/deploy.js
  src/commands/login.js
  src/commands/logout.js
  src/commands/status/index.js
  src/hooks/init.js
  src/lib/fs.js
  src/lib/settings.js
  src/utils/command.js
  src/utils/get-global-config.js
  src/utils/get-global-config.test.js
  src/utils/global-config.js
  src/utils/telemetry/index.js
  tests/command.deploy.test.js
Labels: area: dx, needs docs, type: feature

#1779 test: upgrade ava to v3
  package-lock.json
  package.json
  src/utils/detect-server.test.js
Labels: type: chore

#1785 fix(dev): fix role based access tests
  tests/command.dev.test.js
Labels: type: bug

#1784 feat(command-init): recommend framework specific settings on site creation
  package-lock.json
  package.json
  src/utils/init/utils.js
Labels: type: feature

#1776 Improve robustness of netlify-lambda function-builder-detector
  src/function-builder-detectors/netlify-lambda.js
  src/function-builder-detectors/tests/netlify-lambda.test.js
Labels: type: bug

#1792 fix(dev): fix cookie handling with TM
  package-lock.json
  package.json
  tests/command.dev.test.js
Labels: type: bug

#1795 fix: make ntl dev wait for local server to be ready
  src/commands/dev/index.js
Labels: type: bug

#1810 fix: recover from unauthorized error in @netlify/config call
  src/commands/status/index.js
  src/utils/command.js
Labels: type: bug

#1817 fix: disable local server polling for Next.js
  src/commands/dev/index.js
  src/detectors/next.js
Labels: type: bug

#1823 chore: support Node 15
  .github/workflows/main.yml
Labels: type: chore

#1777 fix(headers): add support for consistent * wildcard
  src/utils/headers.js
  src/utils/headers.test.js
  src/utils/proxy.js
Labels: type: bug
