Repository netlify/cli, pull requests merged in 2021-07, with the labels that each got.

#2816 refactor: move debounced file watcher to separate file
  src/lib/functions/builder.js
  src/lib/functions/runtimes/js/builders/zisi.js
  src/lib/functions/watcher.js
Labels: type: chore

#2817 test(command-dev): pass offline flag by default
  tests/command.dev.test.js
  tests/utils/dev-server.js
Labels: type: chore

#2821 test(command-dev): add framework detection integration tests
  src/utils/detect-server.test.js
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
  tests/utils/dev-server.js
  tests/utils/snapshots.js
Labels: type: chore

#2825 fix(command-dev): fail when framework server exits early
  src/commands/dev/index.js
Labels: type: bug

#2824 refactor(command-dev): extract starting a static server to a separate function
  src/commands/dev/index.js
Labels: type: chore

#2820 docs: update netlify-dev
  docs/netlify-dev.md
Labels: type: bug

#2842 fix(command-dev): use waitPort built-in http request support
  src/commands/dev/index.js
Labels: type: bug

#2875 test(command-functions): skip flaky tests
  tests/command.functions.test.js
Labels: type: chore

#2883 fix(command-dev): don't poll for http requests for vite framework
  src/detectors/vite.js
Labels: type: bug

#2872 fix(command-deploy): update alias description
  docs/commands/deploy.md
  src/commands/deploy.js
Labels: type: bug, type: chore

#2885 chore: remove general CODEOWNERS rule
  .github/CODEOWNERS
Labels: type: chore

#2857 refactor(command-dev): use execa to launch framework server
  npm-shrinkwrap.json
  package.json
  src/commands/dev/index.js
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
  tests/utils/snapshots.js
Labels: type: chore

#2826 refactor: invoke functions from runtime
  .github/workflows/main.yml
  src/lib/functions/background.js
  src/lib/functions/builder.js
  src/lib/functions/form-submissions-handler.js
  src/lib/functions/memoized-build.js
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  src/lib/functions/runtimes/index.js
  src/lib/functions/runtimes/js/builders/netlify-lambda.js
  src/lib/functions/runtimes/js/builders/tests/netlify-lambda.test.js
  src/lib/functions/runtimes/js/builders/zisi.js
  src/lib/functions/runtimes/js/index.js
  src/lib/functions/server.js
  src/lib/functions/synchronous.js
  src/lib/functions/utils.js
  src/lib/functions/watcher.js
  src/utils/difference.js
  tests/serving-functions.test.js
Labels: type: chore

#2901 fix(command-dev): pass full lambda-local result functions server
  src/lib/functions/runtimes/js/index.js
  tests/command.dev.test.js
Labels: type: bug

#2900 chore: remove `safe-join` dependency
  npm-shrinkwrap.json
  package.json
  src/utils/read-repo-url.js
  src/utils/read-repo-url.test.js
Labels: type: bug

#2887 feat: enable processDynamicNodeImports ZISI config property
  src/lib/functions/config.js
Labels: type: feature

#2914 chore: set CHOKIDAR_USEPOLLING in CI
  .github/workflows/main.yml
Labels: type: chore

#2852 refactor: enable and fix fp/no-loops
  .eslintrc.js
  src/commands/env/import.js
  src/commands/env/list.js
  src/commands/init.js
  src/commands/link.js
  src/detectors/utils/jsdetect.js
  src/lib/functions/runtimes/js/builders/netlify-lambda.js
  src/lib/functions/synchronous.js
  src/utils/detect-functions-builder.js
  src/utils/detect-server.js
  src/utils/dev.js
  src/utils/get-global-config.js
  src/utils/get-global-config.test.js
  src/utils/gitignore.js
  src/utils/headers.js
  src/utils/state-config.js
  tests/utils/dev-server.js
  tests/utils/site-builder.js
Labels: type: chore

#2924 chore: temporarily disable problematic tests
  tests/serving-functions.disabled-test.js
Labels: type: chore

#2925 fix(command-functions): inject env variables to functions:serve
  src/commands/functions/serve.js
  tests/command.functions.test.js
Labels: type: bug

#1704 Feat: use framework info
  docs/commands/dev.md
  docs/netlify-dev.md
  npm-shrinkwrap.json
  package.json
  src/commands/dev/index.js
  src/detectors/README.md
  src/detectors/angular.js
  src/detectors/brunch.js
  src/detectors/create-react-app.js
  src/detectors/docusaurus.js
  src/detectors/eleventy.js
  src/detectors/ember.js
  src/detectors/expo.js
  src/detectors/gatsby.js
  src/detectors/gridsome.js
  src/detectors/hexo.js
  src/detectors/hugo.js
  src/detectors/jekyll.js
  src/detectors/middleman.js
  src/detectors/next.js
  src/detectors/nuxt.js
  src/detectors/parcel.js
  src/detectors/phenomic.js
  src/detectors/quasar-v0.17.js
  src/detectors/quasar.js
  src/detectors/react-static.js
  src/detectors/redwoodjs.js
  src/detectors/sapper.js
  src/detectors/stencil.js
  src/detectors/svelte-kit.js
  src/detectors/svelte.js
  src/detectors/utils/jsdetect.js
  src/detectors/vite.js
  src/detectors/vue.js
  src/detectors/vuepress.js
  src/utils/detect-server-settings.js
  src/utils/detect-server.js
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
  tests/utils/snapshots.js
Labels: type: feature

#2692 chore: skip main CI workflow on release branches
  .github/workflows/main.yml
Labels: type: chore

#2933 chore: fix flaky tests in CI
  tests/serving-functions.test.js
  tests/utils/pause.js
Labels: type: chore

#2895 fix(docs): clarify live site creation from tests closes #2541
  .github/workflows/main.yml
  CONTRIBUTING.md
  tests/command.deploy.test.js
Labels: type: bug

#2931 refactor: enable and fix fp/no-proxy
  .eslintrc.js
  src/utils/chalk.js
Labels: type: chore

#2945 chore: make release check cross-OS compatible
  .github/workflows/main.yml
Labels: type: chore

#2944 test(edge-handlers): using new edge-handler default directory
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/utils/site-builder.js
Labels: type: bug, type: chore

#2941 feat: pass zisiEsbuildDynamicImports flag to Netlify Build
  src/lib/build.js
Labels: type: feature

#2946 ci(windows): use default shell
  .github/workflows/main.yml
Labels: type: chore

#2948 chore: use double quotes in workflow command
  .github/workflows/main.yml
Labels: type: chore

#2963 chore: skip npm scripts on pre-release publish
  .github/workflows/pre-release.yml
Labels: type: chore

#2965 chore: upgrade npm in pre-release workflow
  .github/workflows/pre-release.yml
Labels: type: chore

#2966 chore: fix pre-release workflow
  .github/workflows/pre-release.yml
Labels: type: chore

#2971 fix: shorthand notation o for the offline flag fixes #2400
  src/utils/command.js
Labels: type: bug

#2970 fix(command-dev): filter frameworks with no dev command
  src/utils/detect-server-settings.js
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
Labels: type: bug

#2954 feat: add support for internal functions directory
  src/commands/deploy.js
  src/lib/fs.js
  src/lib/functions/registry.js
  src/lib/functions/server.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
  src/utils/functions/index.js
  tests/command.deploy.test.js
  tests/serving-functions.test.js
Labels: type: feature

#2929 feat: add support for Go functions
  npm-shrinkwrap.json
  package.json
  src/lib/functions/local-proxy.js
  src/lib/functions/registry.js
  src/lib/functions/runtimes/go/index.js
  src/lib/functions/runtimes/index.js
  src/lib/functions/runtimes/js/index.js
  src/lib/functions/server.js
  tests/serving-functions-go.test.js
Labels: type: feature

#2981 chore: fossa workflow
  .github/workflows/fossa.yml
Labels: type: bug, type: chore

#2984 chore: increase timeout in tests
  tests/serving-functions-go.test.js
  tests/serving-functions.test.js
Labels: type: chore

#2985 fix: use new arguments syntax
  src/lib/functions/local-proxy.js
Labels: type: bug

#2993 fix: only load Go functions from source
  src/lib/functions/registry.js
  src/lib/functions/runtimes/go/index.js
  src/lib/functions/runtimes/index.js
Labels: type: bug

#3015 test(serving-functions): add CLI output on failure
  tests/serving-functions-go.test.js
  tests/serving-functions.test.js
  tests/utils/dev-server.js
Labels: type: chore

#3019 fix: keep --build flag in deploy message suggestion
  src/commands/deploy.js
Labels: type: bug

#3017 fix(fish): stop git lm utility script path clutter
  src/utils/lm/scripts/fish.sh
Labels: type: bug

#3022 fix(command-status): invoke getToken()
  src/commands/status/index.js
Labels: type: bug

#3024 fix(command-status): fix typo Github -> GitHub
  src/commands/status/index.js
  tests/command.status.test.js
Labels: type: bug

#3029 test(serving-functions): add more logs
  tests/serving-functions-go.test.js
  tests/serving-functions.test.js
Labels: type: chore

#3032 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#3027 chore(ci): skip tests for release-please publish flow
  .github/workflows/release-please.yml
  package.json
Labels: automerge, type: chore

#3034 chore(ci-release-please): add missing condition
  .github/workflows/release-please.yml
Labels: type: chore

#3035 feat: add versioning to `plugins.json`
  src/utils/init/plugins.js
Labels: type: feature

#3041 fix: fix version of `plugins.json`
  src/utils/init/plugins.js
Labels: type: bug

#3037 feat: add Rust functions runtime
  npm-shrinkwrap.json
  package.json
  src/lib/functions/local-proxy.js
  src/lib/functions/registry.js
  src/lib/functions/runtimes/go/index.js
  src/lib/functions/runtimes/index.js
  src/lib/functions/runtimes/rust/index.js
Labels: type: feature

#3047 chore: add util for mocking `execa` calls
  src/lib/fs.js
  src/lib/functions/local-proxy.js
  src/lib/functions/runtimes/go/index.js
  src/utils/execa.js
  tests/serving-functions-go.test.js
  tests/utils/mock-execa.js
Labels: type: chore
