Repository netlify/cli, pull requests merged in 2021-03, with the labels that each got.

#1942 chore: use default rangeStrategy
  renovate.json5
Labels: type: chore

#1950 Add branded README image
  README.md
  cli.png
Labels: type: feature

#1949 fix(command-dev): call middleware next on invalid content-type
  src/utils/detect-server.js
  src/utils/serve-functions.js
  tests/command.dev.test.js
Labels: type: bug

#1970 chore: ignore major updates for 'open' and 'inquirer'
  renovate.json5
Labels: type: chore

#1978 fix(sites-delete): use siteId instead of cwdSiteId for warning messages
  src/commands/sites/delete.js
Labels: type: bug

#1982 chore: remove redundant changelog header in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: chore

#1990 fix: add missing watch command to docs site
  docs/commands/watch.md
  site/src/_app.js
Labels: type: bug

#1988 feat: add a --prodIfUnlocked flag
  docs/commands/deploy.md
  src/commands/deploy.js
Labels: type: feature

#1998 refactor: remove usages of lodash.get
  .eslintrc.js
  src/commands/deploy.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/utils/proxy.js
Labels: type: chore

#2000 refactor: enable and fix promise/no-nesting
  .eslintrc.js
  src/functions-templates/js/fauna-crud/read-all.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
Labels: type: chore

#2001 refactor: enable and fix unicorn/no-array-push-push
  .eslintrc.js
  src/utils/proxy.js
  src/utils/serve-functions.js
Labels: type: chore

#2002 refactor: enable and fix prefer-await-to-then
  .eslintrc.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-crud/create.js
  src/functions-templates/js/fauna-crud/delete.js
  src/functions-templates/js/fauna-crud/read.js
  src/functions-templates/js/fauna-crud/update.js
  src/functions-templates/js/sanity-create/sanity-create.js
  src/functions-templates/js/sanity-groq/sanity-groq.js
  src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
  src/utils/read-repo-url.js
Labels: type: chore

#1836 feat(command-init): recommend build plugins
  package-lock.json
  package.json
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/init/frameworks.js
  src/utils/init/node-version.js
  src/utils/init/plugins.js
  src/utils/init/utils.js
  tests/command.init.test.js
  tests/command.lm.test.js
  tests/utils/mock-api.js
  tests/utils/site-builder.js
Labels: type: feature

#2008 test(command-init): use predictable branch name
  tests/command.init.test.js
  tests/utils/site-builder.js
Labels: type: chore

#1999 fix(command-status): site info is missing for sites without netlify.toml
  src/commands/status/index.js
Labels: type: bug

#1943 feat(command-lm): add PATH configuration for fish shell
  src/utils/lm/install.js
  src/utils/lm/scripts/fish.sh
  src/utils/lm/ui.js
Labels: type: feature

#2019 fix(command-init): use GitHub instead of Github
  src/utils/init/config-github.js
Labels: type: bug

#2017 fix(command-dev): fix query params handling in redirects
  src/utils/proxy.js
  tests/command.dev.test.js
  tests/utils/site-builder.js
Labels: type: bug

#2032 test(command-init): make tests pass on forked PRs
  tests/command.init.test.js
Labels: type: chore

#2007 refactor: enable and fix promise rules
  .eslintrc.js
  src/commands/functions/create.js
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/using-middleware/using-middleware.js
  src/utils/lm/steps.js
  src/utils/rules-proxy.js
  tests/utils/dev-server.js
Labels: type: chore

#2031 fix(command-link): don't modify gitignore if a pattern includes .netlify
  src/utils/gitignore.js
Labels: type: bug

#2026 chore: remove esbuild feature flag
  src/lib/build.js
Labels: init/es-func-bundle, type: chore
