Repository netlify/cli, pull requests merged in 2021-08, with the labels that each got.

#3060 chore: add Rust test
  src/lib/functions/runtimes/rust/index.js
  tests/serving-functions-rust.test.js
Labels: automerge, type: chore

#3071 fix: start functions server if internal functions directory exists
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  src/lib/functions/runtimes/js/builders/zisi.js
  src/lib/functions/runtimes/js/index.js
  src/lib/functions/server.js
Labels: automerge, type: bug

#3078 fix: take internal functions directory into account when assigning functions server port
  src/utils/detect-server-settings.js
Labels: automerge, type: bug

#2920 fix(command-deploy): sync redirects after build
  src/commands/deploy.js
  src/lib/build.js
  tests/command.deploy.test.js
Labels: automerge, type: bug

#3091 feat: add support for manifest file
  docs/commands/deploy.md
  src/commands/deploy.js
  src/lib/build.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
  src/utils/functions/index.js
  tests/assets/bundled-function-1.zip
  tests/command.deploy.test.js
  tests/utils/site-builder.js
Labels: automerge, type: feature

#3096 chore!: update test fixture names
  tests/command.deploy.test.js
  tests/command.functions.test.js
Labels: automerge, type: chore

#3105 chore: pin release-please version
  .github/workflows/release-please.yml
Labels: automerge, type: chore

#3107 fix(command-dev): decode path component before matching redirects
  src/utils/rules-proxy.js
  tests/command.dev.test.js
Labels: automerge, type: bug

#3125 feat: install function template deps in site-level `package.json`
  src/commands/functions/create.js
  tests/command.functions.test.js
Labels: type: feature

#3128 chore: allow codecov step in GitHub Action to fail
  .github/workflows/main.yml
Labels: type: chore

#3127 feat: add TypeScript function template
  src/commands/functions/create.js
  src/functions-templates/ts/hello-world/.netlify-function-template.js
  src/functions-templates/ts/hello-world/hello-world.ts
  src/functions-templates/ts/hello-world/package-lock.json
  src/functions-templates/ts/hello-world/package.json
  src/functions-templates/unused_go/hello-world/hello-world.go
  src/functions-templates/unused_ts/hello-world/hello-world.ts
  src/functions-templates/unused_ts/node-fetch/node-fetch.ts
  src/functions-templates/unused_ts/node-fetch/package.json
  tests/command.functions.test.js
Labels: type: feature

#3134 fix: use variables in function template filenames
  src/commands/functions/create.js
  src/functions-templates/js/apollo-graphql-rest/{{name}}.js
  src/functions-templates/js/apollo-graphql/{{name}}.js
  src/functions-templates/js/auth-fetch/{{name}}.js
  src/functions-templates/js/create-user/{{name}}.js
  src/functions-templates/js/fauna-crud/{{name}}.js
  src/functions-templates/js/fauna-graphql/{{name}}.js
  src/functions-templates/js/google-analytics/{{name}}.js
  src/functions-templates/js/graphql-gateway/{{name}}.js
  src/functions-templates/js/hasura-event-triggered/{{name}}.js
  src/functions-templates/js/hello-world/{{name}}.js
  src/functions-templates/js/identity-signup/{{name}}.js
  src/functions-templates/js/node-fetch/{{name}}.js
  src/functions-templates/js/oauth-passport/{{name}}.js
  src/functions-templates/js/protected-function/{{name}}.js
  src/functions-templates/js/sanity-create/{{name}}.js
  src/functions-templates/js/sanity-groq/{{name}}.js
  src/functions-templates/js/send-email/{{name}}.js
  src/functions-templates/js/serverless-ssr/{{name}}.js
  src/functions-templates/js/set-cookie/{{name}}.js
  src/functions-templates/js/slack-rate-limit/{{name}}.js
  src/functions-templates/js/stripe-charge/{{name}}.js
  src/functions-templates/js/stripe-subscription/{{name}}.js
  src/functions-templates/js/submission-created/{{name}}.js
  src/functions-templates/js/token-hider/{{name}}.js
  src/functions-templates/js/url-shortener/{{name}}.js
  src/functions-templates/js/using-middleware/{{name}}.js
  src/functions-templates/ts/hello-world/{{name}}.ts
Labels: type: bug, automerge

#3137 fix: package up all files from function templates
  package.json
  src/functions-templates/js/README.md
Labels: type: bug

#3144 fix: omit deleted files from log message
  src/commands/functions/create.js
Labels: type: bug

#3152 feat: prints functions proxy output
  src/lib/functions/local-proxy.js
  tests/serving-functions-go.test.js
  tests/serving-functions-rust.test.js
Labels: type: feature, automerge

#3180 feat: add Go function template
  src/commands/functions/create.js
  src/functions-templates/go/hello-world/.netlify-function-template.js
  src/functions-templates/go/hello-world/go.mod
  src/functions-templates/go/hello-world/go.sum
  src/functions-templates/go/hello-world/main.go
Labels: type: feature

#3189 feat: use `netlify-headers-parser`
  npm-shrinkwrap.json
  package.json
  src/utils/headers.js
  src/utils/headers.test.js
  src/utils/proxy.js
Labels: type: feature, automerge

#3194 fix(command-dev): pass framework-info env to sub process
  src/commands/dev/index.js
  src/utils/detect-server-settings.js
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
  tests/utils/snapshots.js
Labels: type: bug, automerge

#3190 chore: move redirects parsing code
  src/utils/redirects.js
  src/utils/redirects.test.js
  src/utils/rules-proxy.js
  src/utils/rules-proxy.test.js
Labels: type: chore, automerge

#3208 feat: use `netlify-headers-parser` for headers path matching
  src/utils/headers.js
  src/utils/headers.test.js
  src/utils/proxy.js
Labels: type: feature, automerge

#3215 fix: support `netlify.toml` headers with `netlify dev`
  src/utils/headers.js
  src/utils/proxy.js
  src/utils/rules-proxy.js
Labels: type: bug, automerge

#3218 fix(command-dev): don't redirect to function server if it doesn't exist
  src/utils/proxy.js
  tests/command.dev.test.js
Labels: type: bug, automerge

#3225 feat: improve error handling of invalid headers/redirects
  src/utils/headers.js
  src/utils/headers.test.js
  src/utils/redirects.js
Labels: type: feature, automerge

#3228 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#3258 chore(kodiak): auto merge renovate minor and patch PRs
  .github/.kodiak.toml
Labels: type: chore, automerge

#3247 feat: add new utilities for warn, error and exit log
  src/utils/command-helpers.js
Labels: type: feature, automerge

#3277 chore(ci): fix don't cache npm cache dir between workflow execs
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/release-please.yml
  .github/workflows/verify-docs.yml
Labels: type: chore, automerge

#3278 fix(command-dev): ensure no orphaned child process on Windows
  src/commands/dev/index.js
Labels: type: bug
