Repository netlify/cli, pull requests merged in 2021-06, with the labels that each got.

#2529 feat: replace mesh-forward with new routing-local-proxy
  npm-shrinkwrap.json
  package.json
  src/utils/traffic-mesh.js
  tests/command.dev.test.js
  tests/command.dev.trace.test.js
Labels: type: chore, type: feature

#2543 feat: Adds RedwoodJS Detector for netlify dev
  src/detectors/redwoodjs.js
Labels: type: feature

#2504 feat: add detector for SvelteKit
  src/detectors/svelte-kit.js
  src/detectors/svelte.js
Labels: type: feature

#2530 fix(performance): load envinfo on demand, disable ts-node
  src/hooks/init.js
  src/index.js
Labels: type: bug

#2576 fix(command-deploy): remove random spinner
  npm-shrinkwrap.json
  package.json
  src/commands/deploy.js
Labels: type: bug

#2585 fix(command-dev): improve initialization time
  src/utils/detect-server.js
  src/utils/get-functions.js
  src/utils/serve-functions.js
Labels: type: bug

#2592 chore: refactor redirects file path logic
  src/utils/rules-proxy.js
Labels: type: chore, type: feature

#2597 feat: use ZISI v2 handler
  src/commands/deploy.js
  src/function-builder-detectors/zisi.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
Labels: type: feature

#2593 feat(command-deploy): refresh configuration when running with --build
  npm-shrinkwrap.json
  package.json
  src/commands/build/index.js
  src/commands/deploy.js
  src/lib/build.js
  tests/command.deploy.test.js
  tests/utils/site-builder.js
Labels: type: feature

#2609 fix: revert b26e51cb740e01a2fda2e8914bb1d632574d0075
  npm-shrinkwrap.json
  package.json
Labels: type: bug

#2599 fix(command-dev): handle Expect:100-continue
  src/utils/proxy.js
  tests/command.dev.test.js
  tests/utils/curl.js
Labels: type: bug

#2633 fix: wait for file watching to be ready with `netlify dev`
  src/utils/serve-functions.js
Labels: type: bug

#2632 chore(site): fix algolia search
  .github/workflows/docsearch.yml
  site/algolia/config.json
  site/src/_layout.js
Labels: type: chore

#2665 fix(command-dev): encode static file names before building URL path
  src/utils/proxy.js
  tests/command.dev.test.js
Labels: type: bug

#2674 fix(deps): fix @netlify/esbuild usage by functions-utils
  npm-shrinkwrap.json
  package.json
Labels: type: bug

#2681 fix(command-dev): use decache instead of clearing the entire cache
  npm-shrinkwrap.json
  package.json
  src/utils/serve-functions.js
Labels: type: bug

#2704 fix(command-dev): handle event triggered background functions
  src/commands/functions/invoke.js
  src/utils/get-functions.js
  src/utils/serve-functions.js
  tests/command.dev.test.js
  tests/command.functions.test.js
Labels: type: bug

#2706 fix(windows): retry getGlobalConfig
  src/utils/get-global-config.js
Labels: type: bug

#2714 feat: reorganise functions serving logic
  src/commands/dev/index.js
  src/commands/functions/serve.js
  src/lib/functions/background.js
  src/lib/functions/builder.js
  src/lib/functions/form-submissions-handler.js
  src/lib/functions/server.js
  src/lib/functions/synchronous.js
  src/lib/functions/utils.js
  src/lib/string.js
  src/utils/serve-functions.js
Labels: type: feature

#2750 ci(docsearch): update to latest version and update schedule
  .github/workflows/docsearch.yml
Labels: type: chore

#2764 fix(deps): pin zisi to 4.4.2
  npm-shrinkwrap.json
  package.json
Labels: type: bug

#2761 fix(command-lm): setting of PATH for Git LFS with fish shell
  src/utils/lm/scripts/fish.sh
Labels: type: bug

#2755 feat(command-build): add offline mode
  docs/commands/build.md
  src/commands/build/index.js
  src/lib/build.js
  tests/command.build.test.js
Labels: type: feature

#2777 chore(deps): ignore major updates for node-version-alias
  renovate.json5
Labels: type: chore

#2792 chore(site): update markdown magic
  README.md
  site/package-lock.json
  site/package.json
  site/scripts/generate-command-data.js
Labels: type: chore

#2788 chore(ci): add prerelease action
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore

#2791 chore(ci): fix status check names
  .github/workflows/benchmark.yml
  .github/workflows/vale.yml
  .github/workflows/verify-docs.yml
Labels: type: chore

#2799 feat: add warning for missing aws-sdk dependency
  src/lib/functions/server.js
  src/lib/functions/synchronous.js
  src/lib/functions/utils.js
  src/lib/log.js
Labels: type: feature

#2440 docs: VS code debugging config & MRE
  docs/functions-dev.md
  docs/vscode.md
  site/src/_app.js
Labels: type: chore

#2808 refactor: abstract `memoizedBuild` util to a separate file
  src/function-builder-detectors/zisi.js
  src/lib/functions/memoized-build.js
Labels: type: chore

#2810 refactor: move `normalizeFunctionsConfig` to a separate file
  src/commands/deploy.js
  src/function-builder-detectors/zisi.js
  src/lib/functions/config.js
Labels: type: chore

#2811 refactor: move function builders to functions lib
  src/function-builder-detectors/README.md
  src/lib/functions/runtimes/js/builders/netlify-lambda.js
  src/lib/functions/runtimes/js/builders/tests/netlify-lambda.test.js
  src/lib/functions/runtimes/js/builders/zisi.js
  src/utils/detect-functions-builder.js
Labels: type: chore
