Repository netlify/cli, pull requests merged in 2021-02, with the labels that each got.

#1830 chore: ignore path-type major updates
  renovate.json5
Labels: type: chore

#1833 fix(command-login): reduce auth timeout, display spinner
  src/utils/command.js
Labels: type: bug

#1837 chore: migrate masterIssue to dependencyDashboard
  renovate.json5
Labels: type: chore

#1804 feat: remove warning for default functions directory
  src/lib/deprecations.js
  src/utils/command.js
  tests/command.test.js
Labels: type: feature

#1856 chore: fix linting and formatting on npm@7
  .eslintrc.js
  package.json
Labels: type: chore

#1844 feat(command-functions-list): remove hidden flag
  README.md
  docs/README.md
  docs/commands/functions.md
  docs/commands/index.md
  src/commands/functions/list.js
Labels: type: feature

#1860 test: allow configuring test account slug
  tests/utils/create-live-test-site.js
Labels: type: chore

#1853 feat(command-functions): update fauna crud template
  src/functions-templates/js/fauna-crud/create-schema.js
  src/functions-templates/js/fauna-crud/create.js
  src/functions-templates/js/fauna-crud/delete.js
  src/functions-templates/js/fauna-crud/package.json
  src/functions-templates/js/fauna-crud/read-all.js
  src/functions-templates/js/fauna-crud/read.js
  src/functions-templates/js/fauna-crud/update.js
Labels: type: feature

#1855 fix(command-dev): handle headers with colon in value
  src/utils/headers.js
  src/utils/headers.test.js
Labels: type: bug

#1489 feat(command-lm): merge netlify-lm-plugin to CLI
  .github/workflows/main.yml
  README.md
  docs/README.md
  docs/commands/index.md
  docs/commands/lm.md
  package-lock.json
  package.json
  site/src/_app.js
  src/commands/lm/index.js
  src/commands/lm/info.js
  src/commands/lm/install.js
  src/commands/lm/setup.js
  src/lib/fs.js
  src/utils/lm/install.js
  src/utils/lm/requirements.js
  src/utils/lm/scripts/bash.sh
  src/utils/lm/scripts/path.ps1
  src/utils/lm/scripts/zsh.sh
  src/utils/lm/steps.js
  src/utils/lm/ui.js
  tests/command.lm.test.js
  tests/utils/mock-api.js
Labels: needs docs, type: feature

#1878 fix(command-dev): pass dev context to '@netlify/config'
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/dev/trace.js
  src/utils/command.js
  src/utils/dev.js
  tests/command.dev.test.js
Labels: type: bug

#1876 chore(deps): update renovate to use rangeStrategy bump
  renovate.json5
Labels: type: chore

#1879 test(command-lm): add uninstall command
  src/commands/lm/uninstall.js
  src/utils/lm/install.js
  tests/command.lm.test.js
Labels: type: chore

#1890 refactor: remove regex usage in site scripts
  site/scripts/generate-command-data.js
  site/src/_app.js
Labels: type: chore

#1887 fix(command-lm-install): fix gitconfig path in windows
  src/utils/lm/install.js
Labels: type: bug

#1899 fix(command-link): retrieve all sites using pagination params
  src/commands/link.js
  src/commands/sites/list.js
  src/lib/api.js
  src/utils/link/link-by-prompt.js
Labels: type: bug

#1897 fix(command-lm-install): remove legacy version on install
  src/utils/lm/install.js
Labels: type: bug

#1901 fix: reduce package size
  package.json
Labels: type: bug

#1912 fix(command-init): use netlify/functions instead of functions
  src/utils/init/utils.js
Labels: type: bug

#1914 feat: add environment variable for esbuild
  src/lib/build.js
Labels: type: feature

#1906 feat: rename trafficMesh flag to edgeHandlers
  src/commands/dev/index.js
  tests/command.dev.test.js
Labels: needs docs, type: feature
