Repository netlify/cli, pull requests merged in 2021-09, with the labels that each got.

#3073 fix: update `InitCommand.description`
  README.md
  docs/README.md
  docs/commands/index.md
  docs/commands/init.md
  src/commands/init.js
  tests/snapshots/command.help.test.js.md
  tests/snapshots/command.help.test.js.snap
Labels: type: chore, type: bug, area: docs, automerge

#3316 fix: use original `event.path` when redirecting to Functions
  src/utils/proxy.js
Labels: type: bug

#3250 chore(docs-vs-debugging): add information on debugging with esbuild
  docs/vscode.md
Labels: type: feature, automerge

#3229 fix: add newline when editing the .gitignore
  src/utils/gitignore.js
Labels: type: bug, automerge

#3310 feat: Support rawUrl and rawQuery in local lambda executions
  src/lib/functions/server.js
  tests/serving-functions.test.js
Labels: type: feature, automerge

#3346 refactor: replace inherited error and exit utils in command.addons
  src/commands/addons/auth.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
Labels: type: chore, automerge

#3349 refactor: replace inherited log utils in src/command/(dev|sites|open)
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
Labels: type: chore, automerge

#3350 refactor: replace catch(_) with catch in try-catch blocks
  scripts/postinstall.js
  site/fs.js
  src/commands/lm/info.js
  src/lib/fs.js
  src/lib/functions/runtimes/go/index.js
  src/lib/functions/server.js
  src/utils/command.js
  src/utils/get-global-config.js
  src/utils/get-global-config.test.js
  src/utils/init/config-github.js
  src/utils/lm/install.js
  tests/serving-functions.test.js
Labels: type: chore, automerge

#3366 refactor: replace inherited log, exit utils in src/commands.(status|api|deploy)
  src/commands/api.js
  src/commands/deploy.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/lib/api.js
  src/utils/deploy/deploy-site.js
  src/utils/edge-handlers.js
Labels: type: chore, automerge

#3369 refactor: replace gotCatch404 with "throwHttpErrors: false"
  tests/command.dev.test.js
Labels: type: chore

#3367 refactor: replace inherited log, exit utils in commands.(build|env|lm|link|unlink)
  src/commands/build/index.js
  src/commands/env/import.js
  src/commands/link.js
  src/commands/lm/setup.js
  src/commands/unlink.js
Labels: type: chore

#3373 refactor: replace inherited log,exit utils in src/commands
  src/commands/init.js
  src/commands/login.js
  src/commands/logout.js
  src/commands/switch.js
  src/commands/watch.js
Labels: type: chore, automerge

#3381 refactor: replace log,exit in utils of dev,functions,link command
  src/commands/addons/config.js
  src/commands/dev/index.js
  src/commands/functions/serve.js
  src/lib/functions/form-submissions-handler.js
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  src/lib/functions/server.js
  src/utils/dev.js
  src/utils/link/link-by-prompt.js
Labels: type: chore

#3382 refactor: replace log,exit in utils of init,addons command
  src/utils/addons/prepare.js
  src/utils/command.js
  src/utils/dev.js
  src/utils/dot-env.js
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/init/node-version.js
  src/utils/init/utils.js
Labels: type: chore, automerge

#3388 chore: remove deprecated bodyParser in favor of express methods
  npm-shrinkwrap.json
  package.json
  src/functions-templates/js/oauth-passport/package.json
  src/functions-templates/js/oauth-passport/{{name}}.js
  src/functions-templates/js/serverless-ssr/app/index.js
  src/functions-templates/js/serverless-ssr/package.json
  src/lib/functions/server.js
  tests/utils/external-server.js
  tests/utils/mock-api.js
Labels: type: chore, automerge

#3392 refactor: split core function of getAgent for better testing
  src/lib/http-agent.js
  src/lib/http-agent.test.js
  src/utils/command.js
Labels: type: chore

#3396 refactor: split core function of loadDotEnvFiles for better testing
  src/utils/dev.js
  src/utils/dot-env.js
  src/utils/dot-env.test.js
Labels: type: chore

#3384 fix: add back missing aws-sdk dep warning
  src/lib/functions/synchronous.js
  src/lib/functions/utils.js
Labels: type: bug

#3399 feat: remove `zisiEsbuildDynamicImports` feature flag
  src/lib/build.js
Labels: type: feature, automerge
