Repository netlify/cli, pull requests merged in 2021-05, with the labels that each got.

#2288 feat: add support for functions.included_files property
  npm-shrinkwrap.json
  package.json
  src/function-builder-detectors/zisi.js
  tests/serving-functions.test.js
Labels: type: feature

#2291 feat: enable sourcemaps for functions
  npm-shrinkwrap.json
  package.json
  src/function-builder-detectors/zisi.js
  tests/serving-functions.test.js
Labels: type: feature

#2298 test(command-addons): use mock api
  tests/command.addons.test.js
  tests/utils/mock-api.js
Labels: type: chore

#2299 test(command-build): use mock api
  src/commands/build/index.js
  tests/command.build.test.js
Labels: type: chore

#2200 chore(ci): add vale
  .github/styles/.gitkeep
  .github/workflows/vale.yml
  .gitignore
  .vale.ini
  CONTRIBUTING.md
Labels: type: chore

#2303 test(command-env): use mock api
  tests/command.addons.test.js
  tests/command.env.test.js
  tests/utils/call-cli.js
  tests/utils/mock-api.js
Labels: type: chore

#2312 fix(command-dev): detect other Jekyll config file names
  src/detectors/jekyll.js
Labels: type: bug

#2307 feat(command-help): add per command help description
  src/lib/help.js
Labels: type: feature

#2315 test(windows): increase port limit and reduce time wait delay
  .github/workflows/main.yml
Labels: type: chore

#2270 feat(command-functions): add serve command
  README.md
  docs/README.md
  docs/commands/functions.md
  docs/commands/index.md
  docs/functions-dev.md
  site/src/_app.js
  src/commands/functions/build.js
  src/commands/functions/list.js
  src/commands/functions/serve.js
  src/utils/dev.js
  src/utils/functions/index.js
  src/utils/serve-functions.js
  tests/command.functions.test.js
Labels: needs docs, type: feature

#2320 docs(functions-dev): fix some typos
  docs/functions-dev.md
Labels: type: bug

#2321 ci(github): skip CLI tests for docs changes
  .github/workflows/main.yml
Labels: type: chore

#2317 feat: extract deploy logic from js-client
  npm-shrinkwrap.json
  package.json
  src/commands/deploy.js
  src/function-builder-detectors/zisi.js
  src/utils/deploy/constants.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-files.js
  src/utils/deploy/hash-files.test.js
  src/utils/deploy/hash-fns.js
  src/utils/deploy/hash-fns.test.js
  src/utils/deploy/hasher-segments.js
  src/utils/deploy/upload-files.js
  src/utils/deploy/util.js
  src/utils/deploy/util.test.js
Labels: type: feature

#2351 fix(deps): update p-map to v4
  npm-shrinkwrap.json
  package.json
Labels: type: bug

#2350 chore(deps): renovate ignore p-map and http-proxy-middleware
  renovate.json5
Labels: type: chore

#2330 fix(postinstall): wrap chalk require
  scripts/postinstall.js
Labels: type: bug

#2378 test(mock-api): use object comparison
  npm-shrinkwrap.json
  tests/command.addons.test.js
  tests/command.env.test.js
  tests/utils/mock-api.js
Labels: type: chore

#2382 fix(command-init): use main instead of master
  src/commands/init.js
Labels: type: bug

#2385 fix(command-link-init): always create gitignore in repo root
  src/commands/init.js
  src/commands/link.js
  src/utils/command.js
  tests/command.link.test.js
  tests/utils/site-builder.js
Labels: type: bug

#2387 fix(command-init): remove functions dir workaround
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/init/utils.js
  tests/command.init.test.js
Labels: type: bug

#2396 chore: run CI tests on Node 16
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/release-please.yml
  .github/workflows/verify-docs.yml
Labels: type: chore

#2392 feat: add warning for native modules
  src/commands/deploy.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
Labels: type: feature

#2421 chore: run CI on latest Node.js
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/release-please.yml
  .github/workflows/verify-docs.yml
Labels: type: chore

#2424 chore: fix test coverage upload
  .github/workflows/main.yml
Labels: type: chore

#2450 test: improve process handling
  npm-shrinkwrap.json
  package.json
  tests/command.dev.test.js
  tests/command.functions.test.js
  tests/utils/dev-server.js
  tests/utils/process.js
Labels: type: chore

#2432 chore(telemetry): switch the telemetry backend via redirects
  functions/telemetry.js
  netlify.toml
Labels: type: chore

#2456 test(command-functions): increase wait port timeout
  tests/command.functions.test.js
Labels: type: chore

#2401 feat(command-init): prompt for base
  npm-shrinkwrap.json
  package.json
  src/lib/path.js
  src/utils/init/config-github.js
  src/utils/init/config-manual.js
  src/utils/init/frameworks.js
  src/utils/init/node-version.js
  src/utils/init/utils.js
  src/utils/lm/install.js
  tests/command.init.test.js
Labels: type: feature

#2462 fix(telemetry): fix tracking of --telemetry-enable flag
  src/hooks/analytics.js
  src/hooks/init.js
  src/utils/command.js
  src/utils/telemetry/index.js
  src/utils/telemetry/request.js
  tests/telemetry.test.js
  tests/utils/mock-api.js
Labels: type: bug

#2471 test(command-deploy): improve hash files/fns tests
  src/utils/deploy/hash-files.test.js
  src/utils/deploy/hash-fns.test.js
Labels: type: chore

#2467 chore(ci): pass --no-audit flag to npm
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/verify-docs.yml
  package.json
Labels: type: chore

#2472 fix(analytics): remove usage as hook
  package.json
  src/commands/addons/auth.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
  src/commands/addons/index.js
  src/commands/addons/list.js
  src/commands/api.js
  src/commands/build/index.js
  src/commands/deploy.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/dev/trace.js
  src/commands/env/get.js
  src/commands/env/import.js
  src/commands/env/index.js
  src/commands/env/list.js
  src/commands/env/set.js
  src/commands/env/unset.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/index.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/functions/serve.js
  src/commands/init.js
  src/commands/link.js
  src/commands/lm/index.js
  src/commands/lm/info.js
  src/commands/lm/install.js
  src/commands/lm/setup.js
  src/commands/lm/uninstall.js
  src/commands/login.js
  src/commands/open/admin.js
  src/commands/open/index.js
  src/commands/open/site.js
  src/commands/sites/config.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/sites/index.js
  src/commands/sites/list.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/commands/switch.js
  src/commands/unlink.js
  src/commands/watch.js
  src/hooks/analytics.js
Labels: type: bug

#2496 fix(telemetry): add the correct content-type header to the request
  src/utils/telemetry/request.js
  tests/utils/mock-api.js
Labels: proj/cli-telemetry, type: bug

#2498 fix(telemetry): add cli user-agent to the request with the cli version included
  src/utils/telemetry/request.js
  tests/telemetry.test.js
  tests/utils/mock-api.js
Labels: proj/cli-telemetry, type: bug

#2487 feat(telemetry): measure duration and status
  src/commands/addons/auth.js
  src/commands/addons/config.js
  src/commands/addons/create.js
  src/commands/addons/delete.js
  src/commands/addons/index.js
  src/commands/addons/list.js
  src/commands/api.js
  src/commands/build/index.js
  src/commands/deploy.js
  src/commands/dev/exec.js
  src/commands/dev/index.js
  src/commands/dev/trace.js
  src/commands/env/get.js
  src/commands/env/import.js
  src/commands/env/index.js
  src/commands/env/list.js
  src/commands/env/set.js
  src/commands/env/unset.js
  src/commands/functions/build.js
  src/commands/functions/create.js
  src/commands/functions/index.js
  src/commands/functions/invoke.js
  src/commands/functions/list.js
  src/commands/functions/serve.js
  src/commands/init.js
  src/commands/link.js
  src/commands/lm/index.js
  src/commands/lm/info.js
  src/commands/lm/install.js
  src/commands/lm/setup.js
  src/commands/lm/uninstall.js
  src/commands/login.js
  src/commands/open/admin.js
  src/commands/open/index.js
  src/commands/open/site.js
  src/commands/sites/create.js
  src/commands/sites/delete.js
  src/commands/sites/index.js
  src/commands/sites/list.js
  src/commands/status/hooks.js
  src/commands/status/index.js
  src/commands/switch.js
  src/commands/unlink.js
  src/commands/watch.js
  src/utils/command.js
  src/utils/telemetry/index.js
  src/utils/telemetry/tracked-command.js
Labels: type: feature
