Repository netlify/cli, pull requests merged in 2021-11, with the labels that each got.

#3563 fix: typo regarding tests in contributing doc
  CONTRIBUTING.md
Labels: type: bug, automerge

#3570 chore: skip problematic test
  tests/serving-functions.test.js
Labels: type: chore, automerge

#3574 fixes the netlify lm:install tests for different shells (like zsh)
  tests/command.lm.test.js
  tests/utils/call-cli.js
Labels: type: chore, type: bug

#3569 chore: replace deprecated querystring package with URLSearchParams API closes #3562
  src/functions-templates/javascript/google-analytics/package-lock.json
  src/functions-templates/javascript/google-analytics/package.json
  src/functions-templates/javascript/google-analytics/{{name}}.js
  src/lib/functions/form-submissions-handler.js
  src/utils/gh-auth.js
Labels: type: chore, type: security, automerge

#3584 fix(dev): fixes an issue where errors in the `dev` command where not shown
  src/utils/dev.js
Labels: type: bug, area: command: dev, automerge

#3592 fix: fix a regression where the creation of a new github token failed inside the init command
  src/commands/addons/auth.js
  src/commands/deploy.js
  src/commands/dev/index.js
  src/commands/open/admin.js
  src/commands/open/site.js
  src/lib/functions/form-submissions-handler.js
  src/utils/command.js
  src/utils/gh-auth.js
  src/utils/gh-auth.test.js
  src/utils/open-browser.js
Labels: type: bug, automerge

#3615 fix: show Background Function plan warning only if site is connected
  src/lib/functions/registry.js
  src/lib/functions/server.js
Labels: type: bug

#3629 fix(init): fixes a wrong import inside the github authentication
  src/utils/init/config-github.js
Labels: type: bug, area: command: init, automerge

#3620 fix(dev): fix wrong rawUrl in the dev command on redirect
  npm-shrinkwrap.json
  package.json
  src/lib/functions/server.js
  src/lib/functions/server.test.js
Labels: type: bug, area: functions, area: command: dev, automerge

#3632 fix(init): fixes an issue where the init command exited with bad credentials
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/init/config-github.test.js
  src/utils/init/config.js
Labels: type: bug, automerge

#3631 fix: resemble Netlify Production logic for base64 encoding more closely
  src/lib/functions/utils.js
  tests/command.dev.test.js
  tests/eleventy.test.js
  tests/serving-functions.test.js
Labels: type: bug, automerge

#3651 chore(docs): add note about netlify-services account
  CONTRIBUTING.md
Labels: type: chore, automerge

#3647 feat: send CLI version in all API requests
  src/utils/command.js
  tests/telemetry.test.js
Labels: type: chore, type: feature, automerge

#3648 chore!: remove node 10 support
  .github/workflows/main.yml
  README.md
  package.json
  src/functions-templates/javascript/google-analytics/package-lock.json
  src/functions-templates/javascript/google-analytics/package.json
  tests/command.deploy.test.js
  tests/command.dev.test.js
  tests/utils/snapshots.js
Labels: type: chore, automerge

#3660 test: fix a test that was failing locally
  tests/telemetry.test.js
Labels: type: chore

#3662 feat(dev): enable the usage of the command property without port
  src/commands/dev/index.js
  src/commands/dev/types.d.ts
  src/utils/detect-server-settings.js
  src/utils/types.d.ts
  tests/framework-detection.test.js
  tests/snapshots/framework-detection.test.js.md
  tests/snapshots/framework-detection.test.js.snap
Labels: needs docs, type: feature, automerge

#3691 chore!: drop support for Node `13`, `14.0.0-14.13.1` and `15`
  package.json
Labels: type: chore, automerge

#3705 chore: remove `fromEntries` polyfill
  npm-shrinkwrap.json
  package.json
  src/commands/env/list.js
  src/lib/functions/form-submissions-handler.js
  src/utils/dev.js
  src/utils/gh-auth.js
Labels: type: chore
