Repository netlify/cli, pull requests merged in 2021-12, with the labels that each got.

#3747 fix: docs update and required status checks
  .github/workflows/main.yml
Labels: type: bug, automerge

#3764 chore: remove unused linting rule exceptions
  .eslintrc.js
Labels: type: chore

#3765 fix: correct Node.js version support for docs site
  site/package.json
  src/functions-templates/javascript/google-analytics/package.json
Labels: type: chore, automerge

#3734 chore: add minimum node.js versions
  docs/README.md
Labels: type: chore

#3783 chore: remove broken readme badges
  README.md
Labels: type: chore, automerge

#3595 feat: add a prompt to modify users .gitignore (closes netlify#2038)
  src/utils/gitignore.js
Labels: type: feature, automerge

#3653 chore: execute tests based on a dependency graph
  .github/workflows/main.yml
  npm-shrinkwrap.json
  package.json
  tools/affected-test.js
  tools/project-graph/dependency-graph.js
  tools/project-graph/file-visitor.js
  tools/project-graph/index.js
  tools/project-graph/types.d.ts
  tools/project-graph/visitor-plugins.js
  tools/tests/affected-files.test.js
  tools/tests/dependency-graph.test.js
  tools/tests/file-visitor-module.test.js
  tools/tests/file-visitor.test.js
  tools/tests/utils/file-systems.js
Labels: type: chore, automerge

#3492 chore: reintroduce test created in #3473
  tests/serving-functions.test.js
Labels: type: chore, automerge

#3841 fix: fixes an issue with yarn pnp on installing
  scripts/postinstall.js
Labels: type: bug, automerge

#3851 fix(switch): fix switch command error when no user logged in
  src/commands/switch/switch.js
Labels: type: bug, automerge

#3850 chore: remove unnecessary windows cmd entry point
  bin/run.cmd
Labels: type: chore, automerge

#3865 chore: fixes an issue on windows
  tools/affected-test.js
Labels: type: chore

#3766 feat: remove unused `--name` flag
  docs/commands/functions.md
  src/commands/functions/functions-list.js
Labels: type: feature, area: command: functions, automerge

#3868 test(command-deploy): fix tests on MacOS CI
  tests/utils/got.js
Labels: type: chore, automerge

#3646 feat: print function URL on first load (closes #3618)
  npm-shrinkwrap.json
  package.json
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  src/lib/functions/server.js
  src/lib/functions/server.test.js
Labels: type: feature, automerge

#3885 feat: add support for deploying scheduled functions
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
Labels: type: feature, automerge

#3872 fix: fixes an issue with npm 6
  .eslintrc.js
  npm-shrinkwrap.json
  package.json
  src/utils/command-helpers.js
Labels: type: bug, automerge

#3782 feat(env-list): hide environment variables values, prompt to show them
  npm-shrinkwrap.json
  package.json
  src/commands/env/env-list.js
  tests/command.env.test.js
  tests/snapshots/command.env.test.js.md
  tests/snapshots/command.env.test.js.snap
  tests/utils/mock-api.js
Labels: type: feature, automerge

#3876 feat(command-env): add migrate subcommand
  README.md
  docs/README.md
  docs/commands/env.md
  docs/commands/index.md
  src/commands/env/env-migrate.js
  src/commands/env/env.js
  tests/command.env.test.js
  tests/snapshots/command.env.test.js.md
  tests/snapshots/command.env.test.js.snap
Labels: type: feature, automerge
