Repository netlify/cli, pull requests merged in 2022-09, with the labels that each got.

#5029 feat: run framework detection and run plugins on netlify build
  src/commands/build/build.js
  src/commands/deploy/deploy.js
  src/lib/build.js
  src/utils/detect-server-settings.js
  src/utils/types.d.ts
  tests/integration/110.command.build.test.js
Labels: type: feature, automerge

#5047 feat: add `baseURL` property to edge functions import maps
  src/lib/edge-functions/internal.js
  tests/integration/100.command.dev.test.js
  tests/integration/utils/site-builder.js
Labels: type: feature

#5053 fix: graph code generator TOML injection
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#5056 fix(graph): fix siteId codegen issues
  npm-shrinkwrap.json
  package.json
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#5083 feat: Revert run framework detection and run plugins on netlify build
  src/commands/build/build.js
  src/commands/deploy/deploy.js
  src/lib/build.js
  src/utils/detect-server-settings.js
  src/utils/types.d.ts
  tests/integration/110.command.build.test.js
Labels: type: feature, automerge

#5090 chore: remove unused plugins-list dependency
  npm-shrinkwrap.json
  package.json
Labels: type: chore

#5016 chore: cleanup eslint
  .eslintrc.js
  src/utils/command-helpers.js
  tools/eslint-rules/index.js
  tools/eslint-rules/no-direct-chalk-import/index.js
  tools/eslint-rules/no-direct-chalk-import/rule.test.js
  tools/eslint-rules/package.json
Labels: type: chore, automerge

#5093 fix(dev): allow passing mock country for geo-based redirects
  src/utils/proxy.js
  src/utils/rules-proxy.js
  tests/integration/100.command.dev.test.js
Labels: type: bug, area: command: dev, area: redirects, automerge

#5094 fix(deps): upgrade wait-port to v1 and listen on correct address for framework
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/http-agent.js
  src/utils/proxy.js
  src/utils/types.d.ts
  tests/integration/20.command.functions.test.js
Labels: type: bug
