Repository netlify/cli, pull requests merged in 2022-10, with the labels that each got.

#5070 Feat: add error page to edge functions for local dev
  src/lib/functions/synchronous.js
  src/lib/render-error-remplate.js
  src/lib/templates/function-error.html
  src/utils/proxy.js
Labels: type: feature

#5128 fix: update template path in package.json
  package.json
Labels: type: chore, type: bug

#5007 fix: follow standard pattern for auto-generated site names
  npm-shrinkwrap.json
  package.json
  src/commands/sites/sites-create-template.js
  src/commands/sites/sites-create.js
  tests/integration/420.command.init.test.js
Labels: type: bug, automerge

#5157 chore: fix grouping of renovate updates
  renovate.json5
Labels: type: chore

#5162 fix: add debug logs to config resolution
  src/commands/base-command.cjs
  src/utils/command-helpers.cjs
Labels: type: chore, type: bug, automerge

#5167 chore: migrate BaseCommand and postinstall to esm
  .eslintrc.cjs
  bin/run.mjs
  package.json
  scripts/postinstall.cjs
  scripts/postinstall.mjs
  site/scripts/generate-command-data.mjs
  src/commands/base-command.mjs
  src/commands/dev/dev.cjs
  src/commands/index.cjs
  src/commands/index.mjs
  src/commands/main.mjs
  src/lib/completion/index.cjs
  tests/integration/140.command.sites.test.cjs
  tests/unit/lib/completion/completion.test.cjs
Labels: type: chore

#5143 chore: kebab-case post-processing flag
  docs/commands/env.md
  src/commands/env/env-get.cjs
  src/commands/env/env-list.cjs
  src/commands/env/env-set.cjs
  src/utils/env/index.cjs
  tests/integration/650.command.envelope.test.cjs
  tests/unit/utils/env/index.test.cjs
Labels: type: chore, automerge

#5191 chore: print env var scope during ntl dev
  src/commands/dev/dev.cjs
Labels: type: chore, automerge, echoes/initiative: americas/secret-management

#5193 fix: fix one more instance of post_processing in broken test
  tests/integration/650.command.envelope.test.cjs
Labels: type: bug, automerge

#5197 feat: support in-source configuration in edge functions
  src/lib/build.cjs
  src/lib/edge-functions/registry.cjs
  tests/integration/100.command.dev.test.cjs
  tests/integration/utils/site-builder.cjs
Labels: type: feature, automerge

#5194 chore: remove beta tags from CLI and docs
  README.md
  docs/README.md
  docs/commands/env.md
  docs/commands/index.md
  src/commands/env/env.cjs
Labels: type: chore
