Repository netlify/cli, pull requests merged in 2022-03, with the labels that each got.

#4362 fix: move config watcher to graph command
  docs/commands/dev.md
  src/commands/base-command.js
  src/commands/dev/dev.js
  src/utils/dev.js
Labels: type: bug, automerge

#4376 fix: remove `zisi_pure_esm` feature flag from ZISI
  src/utils/deploy/hash-fns.js
Labels: type: bug, automerge

#4404 fix: pass `context` to `@netlify/build`
  src/lib/build.js
Labels: type: bug

#4327 feat(command-deploy): allow support for deploying by site name
  docs/commands/deploy.md
  src/commands/deploy/deploy.js
  tests/integration/210.command.deploy.test.js
Labels: type: feature, automerge

#4382 feat(sites): Repo shorthand for create:site-template
  docs/commands/sites.md
  src/commands/sites/sites-create-template.js
  src/utils/sites/utils.js
  tests/integration/140.command.sites.test.js
Labels: type: feature

#4395 fix(functions): stop providing clientContext to background functions
  src/lib/functions/server.js
  tests/integration/100.command.dev.test.js
Labels: type: bug, automerge

#4409 feat(dev-graph): track graph flag usage
  src/commands/dev/dev.js
Labels: type: feature, automerge

#4425 chore: use GitHub forms for new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: type: chore

#4436 ci(delta-action): use v2
  .github/workflows/benchmark.yml
Labels: type: chore

#4427 feat(sites): clone the generated repo #4411
  npm-shrinkwrap.json
  package.json
  src/commands/sites/sites-create-template.js
Labels: type: feature, automerge

#4442 docs: fix typo in netlify-dev
  docs/netlify-dev.md
Labels: type: bug, area: docs

#4455 fix: pass through cwd flag in getBuildOptions
  src/lib/build.js
Labels: type: bug

#4490 fix: polling for API Authentication
  src/commands/dev/dev.js
Labels: type: bug, automerge

#4491 feat: add local dev support for Go scheduled functions
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  tests/integration/20.command.functions.test.js
  tests/integration/630.serving-functions-go.test.js
Labels: type: feature, type: bug, echoes/intent: customer-value

#4493 feat(dev-graph): populate X-Nf-Graph-Token header
  src/lib/functions/server.js
Labels: type: feature, automerge

#4495 feat: added scheduled functions template for Go
  package.json
  src/functions-templates/go/scheduled-function/.netlify-function-template.js
  src/functions-templates/go/scheduled-function/go.mod
  src/functions-templates/go/scheduled-function/go.sum
  src/functions-templates/go/scheduled-function/netlify.toml
  src/functions-templates/go/scheduled-function/src/hourly-schedule/main.go
Labels: type: feature, echoes/intent: customer-value

#4486 feat: improve functions error messages
  package.json
  src/lib/functions/server.js
  src/lib/functions/synchronous.js
  src/lib/functions/templates/function-error.html
Labels: type: feature, echoes/intent: customer-value
