Repository netlify/cli, pull requests merged in 2022-11, with the labels that each got.

#5200 fix: ensure HMR requests can be streamed
  package.json
  src/utils/proxy.cjs
  tests/integration/100.command.dev.test.cjs
  tests/integration/snapshots/320.command.help.test.cjs.md
  tests/integration/snapshots/320.command.help.test.cjs.snap
Labels: type: bug

#5204 chore: fix detection of affected tests
  tools/affected-test.mjs
  tools/project-graph/file-visitor.mjs
Labels: type: chore

#5231 fix: added missing mock geo data
  src/lib/geo-location.cjs
  tests/unit/lib/geo-location.test.cjs
Labels: type: bug

#5261 chore: convert more commands to ESM
  src/commands/deploy/deploy.mjs
  src/commands/dev/dev-exec.mjs
  src/commands/dev/dev.mjs
  src/commands/dev/index.cjs
  src/commands/dev/index.mjs
  src/commands/env/env-clone.mjs
  src/commands/env/env-get.mjs
  src/commands/env/env-import.mjs
  src/commands/env/env-list.mjs
  src/commands/env/env-set.mjs
  src/commands/env/env-unset.mjs
  src/commands/env/env.mjs
  src/commands/env/index.cjs
  src/commands/env/index.mjs
  src/commands/graph/graph-config-write.mjs
  src/commands/graph/graph-edit.mjs
  src/commands/graph/graph-handler.mjs
  src/commands/graph/graph-init.mjs
  src/commands/graph/graph-library.mjs
  src/commands/graph/graph-operations.mjs
  src/commands/graph/graph-pull.mjs
  src/commands/graph/graph.mjs
  src/commands/graph/index.cjs
  src/commands/graph/index.mjs
  src/commands/init/init.mjs
  src/commands/link/index.cjs
  src/commands/link/index.mjs
  src/commands/link/link.mjs
  src/commands/lm/index.cjs
  src/commands/lm/index.mjs
  src/commands/lm/lm-info.mjs
  src/commands/lm/lm-install.mjs
  src/commands/lm/lm-setup.mjs
  src/commands/lm/lm-uninstall.mjs
  src/commands/lm/lm.mjs
  src/commands/main.mjs
  src/commands/sites/sites-create.mjs
Labels: type: chore, automerge
