Repository netlify/cli, pull requests merged in 2022-02, with the labels that each got.

#4163 fix: supply next_run for all scheduled functions calls
  src/commands/functions/functions-invoke.js
  src/lib/functions/netlify-function.js
  src/lib/functions/server.js
  tests/command.functions.test.js
Labels: type: bug, automerge

#4172 fix: revert "fix(deps): update dependency netlify-onegraph-internal to v0.0.18 (#4170)"
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#4143 chore: migrate docs to es modules
  package.json
  site/config.js
  site/config.mjs
  site/fs.js
  site/fs.mjs
  site/package.json
  site/scripts/docs.mjs
  site/scripts/generate-command-data.mjs
  site/sync.mjs
  site/watch.mjs
Labels: type: chore, automerge

#4169 Graph improvements
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/530.graph-codegen.test.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: project, automerge

#4167 chore: inject the Authlify Token in `netlify dev`
  package.json
  src/commands/dev/dev.js
  src/lib/functions/server.js
  src/utils/dev.js
Labels: type: chore

#4145 feat(functions): add scheduled functions templates
  src/functions-templates/javascript/scheduled-function/.netlify-function-template.js
  src/functions-templates/javascript/scheduled-function/package.json
  src/functions-templates/javascript/scheduled-function/{{name}}.js
  src/functions-templates/typescript/scheduled-function/.netlify-function-template.js
  src/functions-templates/typescript/scheduled-function/package.json
  src/functions-templates/typescript/scheduled-function/{{name}}.ts
Labels: type: feature, automerge

#4177 test(command-functions): update to match templates
  tests/integration/20.command.functions.test.js
Labels: type: chore, automerge

#4146 fix: function:serve shows undefined port in url
  src/lib/functions/netlify-function.js
  tests/integration/20.command.functions.test.js
Labels: type: bug, automerge

#4109 fix: external redirects not being matched correctly closes #3770
  src/utils/proxy.js
  tests/integration/0.command.dev.test.js
Labels: type: bug, automerge

#4140 test: replace proxyquire with rewiremock as it works with esm as well
  .gitignore
  npm-shrinkwrap.json
  package.json
  src/lib/exec-fetcher.js
  tests/integration/utils/rewiremock.js
  tests/unit/lib/exec-fetcher.test.js
Labels: type: chore, automerge

#4158 chore: migrate affected tests to esm
  package.json
  tools/affected-test.mjs
  tools/project-graph/dependency-graph.mjs
  tools/project-graph/file-visitor.mjs
  tools/project-graph/index.js
  tools/project-graph/index.mjs
  tools/project-graph/types.d.ts
  tools/project-graph/visitor-plugins.mjs
  tools/tests/affected-files.test.js
  tools/tests/affected-files.test.mjs
  tools/tests/dependency-graph.test.mjs
  tools/tests/file-visitor-module.test.mjs
  tools/tests/file-visitor.test.mjs
  tools/tests/utils/file-systems.mjs
Labels: type: chore, automerge

#4183 feat: Show edit graph link on dev startup, send operations library edits to UI, and run prettier (if available) on code output
  src/commands/dev/dev.js
  src/commands/graph/graph-edit.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: feature, automerge

#3948 feat: implement create site from template feature
  README.md
  docs/README.md
  docs/commands/index.md
  docs/commands/sites.md
  src/commands/sites/sites-create-template.js
  src/commands/sites/sites-create.js
  src/commands/sites/sites.js
  src/utils/sites/utils.js
  tests/integration/140.command.sites.test.js
Labels: type: feature, automerge

#4186 feat: additional `graph` commands, extra graph codegen tests, and type definitions
  .gitignore
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-handler.js
  src/commands/graph/graph-library.js
  src/commands/graph/graph-operations.js
  src/commands/graph/graph-pull.js
  src/commands/graph/graph.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  src/utils/command-helpers.js
  tests/integration/530.graph-codegen.test.js
  tests/integration/assets/netlifyGraphOperationsLibrary.graphql
  tests/integration/assets/netlifyGraphSchema.graphql
  tests/integration/snapshots/220.command.graph.test.js.md
  tests/integration/snapshots/220.command.graph.test.js.snap
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: feature, type: bug, automerge

#4029 chore: automatic update contributors list
  .github/workflows/contributors.yml
  package.json
Labels: type: chore, automerge

#4185 fix: make site suggestion flow consistent
  src/commands/sites/sites-create.js
Labels: type: bug

#4216 fix: update warning message and graph codegen library output
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#4219 chore(contributors-action): use built in token
  .github/workflows/contributors.yml
Labels: type: chore, automerge

#4240 fix: handle content-type headers with charset
  src/lib/functions/utils.js
  tests/integration/20.command.functions.test.js
Labels: type: bug, automerge

#4227 fix: send analytics on successful commands
  bin/run
  src/commands/base-command.js
  tests/integration/240.telemetry.test.js
Labels: type: bug, automerge

#4239 feat: Graph config netlify directive
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-config-write.js
  src/commands/graph/graph.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/530.graph-codegen.test.js
  tests/integration/snapshots/220.command.graph.test.js.md
  tests/integration/snapshots/220.command.graph.test.js.snap
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: feature, automerge

#4247 fix(deps): regenerate lock file
  npm-shrinkwrap.json
Labels: type: bug, automerge

#4249 chore: pin vale action version
  .github/workflows/vale.yml
Labels: type: chore, automerge

#4251 fix: update dep and remove @netlify directive SDL definition in output
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4255 chore(vale): add continue-on-error
  .github/workflows/vale.yml
Labels: type: chore, automerge

#4235 feat: monitor whether API Authentication has been enabled
  src/commands/dev/dev.js
  src/commands/functions/functions-serve.js
  src/lib/functions/server.js
  src/utils/dev.js
Labels: type: feature, automerge

#4257 chore: add `NETLIFY_GRAPH_TOKEN` to env too
  src/lib/functions/server.js
Labels: type: chore, automerge

#4263 feat: Graph additional cli session metadata
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-edit.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: feature, automerge

#4267 feat: refresh graph dx
  src/commands/graph/graph-config-write.js
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-handler.js
  src/commands/graph/graph-library.js
  src/commands/graph/graph-pull.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: feature, automerge

#4287 chore: update getting-started.md
  docs/getting-started.md
Labels: type: bug, automerge

#4276 feat: fuzzy search for graph:handler
  src/commands/graph/graph-handler.js
  src/lib/one-graph/cli-client.js
Labels: type: feature, automerge

#4285 feat: mark graph sessions as inactive so they don't show up in any UI
  src/commands/dev/dev.js
  src/commands/graph/graph-edit.js
  src/lib/one-graph/cli-client.js
Labels: type: feature, automerge

#4298 fix: in graph:handler, still allow user provided input
  src/commands/graph/graph-handler.js
Labels: type: bug, automerge

#4268 feat: `netlify dev --graph`: watch config.toml and reload automatically
  src/commands/base-command.js
  src/commands/dev/dev.js
  src/lib/functions/registry.js
  src/lib/functions/watcher.js
  src/lib/one-graph/cli-client.js
  src/utils/command-helpers.js
Labels: type: feature, automerge

#4300 fix: add missing netlify graph tokens in env
  src/commands/dev/dev.js
  src/lib/functions/server.js
Labels: type: bug

#4308 fix: graph language
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: chore, type: bug

#4316 fix: no option in Suggestion prompt (#4303)
  src/commands/main.js
Labels: type: bug

#4323 chore(ci): don't run update contributors on forked PRs
  .github/workflows/contributors.yml
Labels: type: chore, automerge

#4319 fix: npm run docs on Windows (#3973)
  site/scripts/docs.mjs
Labels: type: bug

#4321 feat: env_files in netlify.toml
  docs/netlify-dev.md
  src/commands/dev/dev-exec.js
  src/commands/dev/dev.js
  src/commands/dev/types.d.ts
  src/commands/functions/functions-create.js
  src/commands/functions/functions-serve.js
  src/utils/dev.js
  src/utils/dot-env.js
  tests/integration/300.command.dev.test.js
Labels: type: feature

#4360 feat: pass `nodeVersion` and feature flags to zip-it-and-ship-it
  src/commands/deploy/deploy.js
  src/lib/functions/config.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-fns.js
Labels: type: feature

#4379 chore(deps): renovate ignore netlify-onegraph-internal
  renovate.json5
Labels: type: chore, automerge

#4396 test(e2e): run in serial
  .github/workflows/e2e-test.yml
  e2e/install.e2e.mjs
Labels: type: chore, automerge

#4363 feat: inject netlify graph environment variables during `ntl build`
  src/commands/build/build.js
Labels: type: feature, automerge
