Repository netlify/cli, pull requests merged in 2022-07, with the labels that each got.

#4760 fix: use correct paths when deploying edge functions on Windows
  src/lib/edge-functions/deploy.js
  tests/integration/210.command.deploy.test.js
Labels: type: bug

#4746 chore: CODEOWNERS update 202206
  .github/CODEOWNERS
Labels: type: chore, automerge

#4770 fix: update minimum required version of commander to 9.2.0
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#4774 chore: split package size workflow to make it work for PRs from forks
  .github/workflows/benchmark-post.yml
  .github/workflows/benchmark.yml
Labels: type: chore

#4776 feat: connect to a cloud session
  docs/commands/dev.md
  src/commands/dev/dev.js
  src/lib/one-graph/cli-client.js
Labels: type: feature, automerge

#4750 fix: replace ansi2html with ansi-to-html
  npm-shrinkwrap.json
  package.json
  src/lib/functions/scheduled.js
Labels: type: security, automerge

#4783 chore: vendor wait-port to unblock CI
  .gitignore
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/http-agent.js
  tests/integration/20.command.functions.test.js
  vendor/wait-port/LICENSE
  vendor/wait-port/README.md
  vendor/wait-port/index.d.ts
  vendor/wait-port/lib/errors/connection-error.js
  vendor/wait-port/lib/errors/target-error.js
  vendor/wait-port/lib/errors/validation-error.js
  vendor/wait-port/lib/extract-target.js
  vendor/wait-port/lib/output-functions/dots.js
  vendor/wait-port/lib/output-functions/index.js
  vendor/wait-port/lib/output-functions/silent.js
  vendor/wait-port/lib/validate-parameters.js
  vendor/wait-port/lib/wait-port.js
  vendor/wait-port/package.json
Labels: type: chore, automerge

#4759 fix: resolve missing output when using --json
  package.json
  src/commands/deploy/deploy.js
Labels: type: bug, automerge

#4748 fix: functions with name matching config prop cause crash
  src/lib/functions/registry.js
  tests/unit/lib/functions/registry.test.js
Labels: type: bug

#4789 fix: Update getTemplatesFromGitHub to retrieve more repositories
  src/commands/sites/sites-create-template.js
  src/utils/sites/utils.js
  tests/integration/140.command.sites.test.js
Labels: type: bug, area: command: sites, automerge

#4788 fix(deps): update wait-port to 0.2.14
  .gitignore
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/http-agent.js
  tests/integration/20.command.functions.test.js
  vendor/wait-port/LICENSE
  vendor/wait-port/README.md
  vendor/wait-port/index.d.ts
  vendor/wait-port/lib/errors/connection-error.js
  vendor/wait-port/lib/errors/target-error.js
  vendor/wait-port/lib/errors/validation-error.js
  vendor/wait-port/lib/extract-target.js
  vendor/wait-port/lib/output-functions/dots.js
  vendor/wait-port/lib/output-functions/index.js
  vendor/wait-port/lib/output-functions/silent.js
  vendor/wait-port/lib/validate-parameters.js
  vendor/wait-port/lib/wait-port.js
  vendor/wait-port/package.json
Labels: type: bug, automerge

#4708 feat: add user assigned mock geo for edge local dev
  docs/commands/dev.md
  src/commands/dev/dev.js
  src/lib/edge-functions/proxy.js
  src/lib/geo-location.js
  src/utils/proxy.js
  tests/integration/660.command.dev.geo.test.js
  tests/unit/lib/geo-location.test.js
Labels: needs docs, type: feature

#4778 chore(graph): refactor service.service and use the new JWT instead of nfToken
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-pull.js
  src/lib/one-graph/cli-client.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: chore, automerge

#4790 chore: send pr number from one to the other workflow
  .github/workflows/benchmark-post.yml
  .github/workflows/benchmark.yml
Labels: type: chore, automerge

#4795 chore: rename `env:migrate` to `env:clone`
  README.md
  docs/README.md
  docs/commands/env.md
  docs/commands/index.md
  src/commands/env/env-clone.js
  src/commands/env/env.js
  tests/integration/610.command.env.test.js
  tests/integration/650.command.envelope.test.js
  tests/integration/snapshots/610.command.env.test.js.md
  tests/integration/snapshots/610.command.env.test.js.snap
  tests/integration/snapshots/650.command.envelope.test.js.md
  tests/integration/snapshots/650.command.envelope.test.js.snap
Labels: type: chore

#4802 fix(graph): regressions introduced during JWT migration
  src/lib/one-graph/cli-client.js
Labels: type: bug, automerge

#4803 fix(graph): use graphJWT in more places
  src/commands/graph/graph-edit.js
  src/lib/one-graph/cli-client.js
Labels: type: bug, automerge

#4820 chore: fix country command + docs typo
  docs/commands/dev.md
  src/commands/dev/dev.js
Labels: type: chore

#4827 Docs: add Git LFS dependency to contribution guide
  CONTRIBUTING.md
Labels: type: chore, automerge

#4832 fix(graph): use the JWT correctly in `refetchAndGenerateFromOneGraph`
  src/commands/graph/graph-pull.js
Labels: type: bug, automerge

#4822 feat: simplify country mock docs
  docs/commands/dev.md
  src/commands/dev/dev.js
Labels: type: feature, automerge

#4821 fix: fix cache error with geo country mock
  src/lib/geo-location.js
Labels: type: bug

#4842 feat: deprecate `netlify:edge` in function templates
  src/functions-templates/typescript/abtest/{{name}}.ts
  src/functions-templates/typescript/geolocation/{{name}}.ts
  src/functions-templates/typescript/json/{{name}}.ts
  src/functions-templates/typescript/log/{{name}}.ts
  src/functions-templates/typescript/set-cookies/{{name}}.ts
  src/functions-templates/typescript/set-req-header/{{name}}.ts
  src/functions-templates/typescript/set-res-header/{{name}}.ts
  src/functions-templates/typescript/transform-response/{{name}}.ts
Labels: type: feature

#4841 feat: add retry count parameter to function uploads
  src/utils/deploy/upload-files.js
  tests/unit/utils/deploy/upload-files.test.js
Labels: type: feature, automerge

#4835 fix: proxy server for Node.js 17/18
  src/utils/proxy.js
  tests/integration/400.command.dev.test.js
  tests/integration/500.command.dev.test.js
Labels: type: bug, automerge

#4860 fix: correctly create edge function directory when running in custom cwd
  src/lib/edge-functions/deploy.js
  src/utils/deploy/deploy-site.js
  tests/integration/210.command.deploy.test.js
  tests/integration/utils/site-builder.js
Labels: type: bug

#4709 feat: alias ntl dev to ntl develop
  src/commands/dev/dev.js
Labels: type: feature, automerge

#4863 fix: prevent promptEditorHelper to run if running tests in vscode
  src/lib/edge-functions/editor-helper.js
Labels: type: bug

#4865 fix(graph): fetch enabled services for the session instead of the app
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-client.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#4866 fix(deps): update netlify-graph-internal
  npm-shrinkwrap.json
  package.json
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#4857 feat: pass site information to edge function context in dev command
  package.json
  src/commands/dev/dev.js
  src/lib/edge-functions/headers.js
  src/lib/edge-functions/proxy.js
  src/utils/proxy.js
  tests/integration/100.command.dev.test.js
Labels: type: feature

#4870 test: move site info header creation to function and write unit test for function
  src/lib/edge-functions/proxy.js
  tests/unit/lib/edge-functions/create-site-info-header.test.js
Labels: type: chore

#4878 fix(graph): fix graph:pull and codegen bugs
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-pull.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge
