Repository netlify/cli, pull requests merged in 2022-04, with the labels that each got.

#4499 fix: fallback should there be an error getting the functions error page template
  package.json
  src/lib/functions/synchronous.js
Labels: type: bug, automerge

#4550 feat!: add support for Edge Functions
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  README.md
  docs/README.md
  docs/commands/dev.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/base-command.js
  src/commands/deploy/deploy.js
  src/commands/dev/dev-trace.js
  src/commands/dev/dev.js
  src/commands/main.js
  src/commands/recipes/common.js
  src/commands/recipes/index.js
  src/commands/recipes/recipes-list.js
  src/commands/recipes/recipes.js
  src/lib/api.js
  src/lib/edge-functions/consts.js
  src/lib/edge-functions/deploy.js
  src/lib/edge-functions/editor-helper.js
  src/lib/edge-functions/headers.js
  src/lib/edge-functions/index.js
  src/lib/edge-functions/internal.js
  src/lib/edge-functions/proxy.js
  src/lib/edge-functions/registry.js
  src/lib/functions/registry.js
  src/recipes/vscode/index.js
  src/recipes/vscode/settings.js
  src/utils/command-helpers.js
  src/utils/deploy/deploy-site.js
  src/utils/deploy/hash-files.js
  src/utils/deploy/hasher-segments.js
  src/utils/functions/edge-handlers.js
  src/utils/functions/index.js
  src/utils/index.js
  src/utils/proxy.js
  src/utils/traffic-mesh.js
  tests/integration/0.command.dev.test.js
  tests/integration/100.command.dev.test.js
  tests/integration/200.command.dev.test.js
  tests/integration/210.command.deploy.test.js
  tests/integration/300.command.dev.test.js
  tests/integration/400.command.dev.test.js
  tests/integration/410.command.dev.trace.test.js
  tests/integration/500.command.dev.test.js
  tests/integration/640.command.recipes.test.js
  tests/integration/snapshots/320.command.help.test.js.md
  tests/integration/snapshots/320.command.help.test.js.snap
  tests/integration/snapshots/640.command.generate.test.js.md
  tests/integration/snapshots/640.command.generate.test.js.snap
  tests/integration/snapshots/640.command.recipes.test.js.md
  tests/integration/snapshots/640.command.recipes.test.js.snap
  tests/integration/utils/dev-server.js
  tests/integration/utils/handle-questions.js
  tests/integration/utils/site-builder.js
  tests/unit/utils/deploy/hash-files.test.js
Labels: type: feature

#4555 feat: change order of Edge Functions execution
  src/lib/edge-functions/registry.js
Labels: type: feature

#4554 feat: warn about orphaned Edge Function declarations
  src/lib/edge-functions/proxy.js
  src/lib/edge-functions/registry.js
Labels: type: feature

#4563 chore: Add init command tests to verify framework specific build directories
  site/package-lock.json
  tests/integration/420.command.init.test.js
Labels: type: chore

#4566 feat: add geolocation data to Netlify Dev
  docs/commands/dev.md
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/edge-functions/headers.js
  src/lib/edge-functions/proxy.js
  src/lib/geo-location.js
  src/utils/proxy.js
  tests/integration/130.eleventy.test.js
  tests/integration/400.command.dev.test.js
  tests/integration/500.command.dev.test.js
  tests/integration/510.hugo.test.js
  tests/lib/local-ip.js
  tests/unit/lib/geo-location.test.js
Labels: type: feature
