Repository netlify/cli, pull requests merged in 2022-05, with the labels that each got.

#4567 feat: add HTTPS support for Edge Functions in Netlify Dev
  .github/workflows/main.yml
  .gitignore
  certconf
  npm-shrinkwrap.json
  package.json
  src/lib/edge-functions/headers.js
  src/lib/edge-functions/proxy.js
  src/utils/detect-server-settings.js
  tests/integration/200.command.dev.test.js
  tests/integration/assets/cert.pem
  tests/integration/assets/key.pem
Labels: type: feature, automerge

#4576 fix: watch edge function dependencies
  src/lib/edge-functions/proxy.js
  src/lib/edge-functions/registry.js
  src/utils/proxy.js
Labels: type: bug, automerge

#4581 chore: include edge functions file watcher tests
  tests/integration/100.command.dev.test.js
Labels: type: chore

#4562 feat: make deploy command bundle edge functions
  src/commands/deploy/deploy.js
Labels: type: feature, automerge

#4604 fix: pass correct protocol to functions server
  src/lib/functions/server.js
  tests/integration/200.command.dev.test.js
  tests/integration/300.command.dev.test.js
Labels: type: bug, automerge

#4605 fix: use correct protocol when displaying function URL
  src/lib/functions/netlify-function.js
Labels: type: bug, automerge

#4628 chore: Downgrade release-please to make it work for now
  .github/workflows/release-please.yml
  package.json
Labels: type: chore

#4632 fix: correctly support multiValueHeaders in rust functions during development
  src/lib/functions/runtimes/rust/index.js
  tests/unit/lib/functions/runtimes/rust/index.test.js
Labels: type: bug, area: functions, automerge

#4651 chore(deps): downgrade googlecloudplatform/release-please-action action to v3.1.4
  .github/workflows/release-please.yml
  renovate.json5
Labels: type: chore, automerge

#4633 chore: remove execa mock after dev server closed
  tests/integration/620.serving-functions-rust.test.js
Labels: type: chore, area: ci, automerge

#4615 feat: support for Edge Functions debugging
  docs/commands/dev.md
  package.json
  src/commands/dev/dev.js
  src/lib/edge-functions/proxy.js
  src/utils/proxy.js
Labels: type: feature
