Repository netlify/cli, pull requests merged in 2022-01, with the labels that each got.

#3930 fix(site): fix wrong regex
  site/src/_layout.js
Labels: type: chore

#3931 Remove superfluous arguments
  site/scripts/docs.js
  src/utils/deploy/upload-files.js
  src/utils/rules-proxy.js
Labels: type: bug

#3937 fix: fix a few typos
  src/commands/base-command.js
  src/utils/addons/prompts.js
  src/utils/traffic-mesh.js
Labels: type: bug

#3944 chore(site): optimize logo
  site/src/_layout.js
Labels: type: chore, automerge

#3938 chore: add CodeQL Action
  .github/workflows/codeql.yml
Labels: type: chore, automerge

#3949 chore(site): use Node.js 16
  netlify.toml
Labels: type: chore, automerge

#3933 fix(deps): remove unused dependencies
  .eslintrc.js
  npm-shrinkwrap.json
  package.json
  renovate.json5
  site/package-lock.json
  site/package.json
Labels: type: chore, automerge

#3940 fix: replace make-dir package with native
  npm-shrinkwrap.json
  package.json
  src/lib/functions/runtimes/js/builders/zisi.js
  src/utils/state-config.js
Labels: type: bug

#3957 fix: correct GitHub capitalization
  docs/README.md
  src/commands/functions/functions-create.js
  src/commands/init/init.js
  src/functions-templates/javascript/serverless-ssr/app/index.js
  src/utils/gh-auth.js
  src/utils/init/config-github.js
  src/utils/read-repo-url.js
Labels: type: bug, automerge

#3965 chore(gh-auth): minor refactoring
  src/utils/gh-auth.js
Labels: type: bug

#3939 chore: replace nyc with c8
  .gitignore
  npm-shrinkwrap.json
  package.json
  tools/affected-test.js
Labels: type: chore

#3863 fix(functions): fixes an issue where the functions could not be served
  src/lib/functions/registry.js
  src/lib/functions/server.test.js
Labels: type: bug, automerge

#3974 fix(telemetry): remove always true condition
  src/utils/telemetry/validation.js
Labels: type: bug, automerge

#3995 fix: pin colors to 1.4.0
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#3999 fix: remove colors as a direct dependency
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#3971 fix: identity default for function:invoke w/o arg
  src/commands/functions/functions-invoke.js
  tests/command.functions.test.js
Labels: type: bug, automerge

#4003 fix: ignore function files with .ZIP extension
  src/lib/functions/registry.js
Labels: type: bug, automerge

#4019 chore: cleanup .gitignore
  .gitignore
Labels: type: chore, automerge

#4027 fix: add `schedule` property to normalised config
  src/lib/functions/config.js
Labels: type: bug, automerge

#4020 feat(command-dev): support frameworks without a port
  npm-shrinkwrap.json
  package.json
  src/utils/detect-server-settings.js
  src/utils/types.d.ts
  tests/framework-detection.test.js
  tests/utils/dev-server.js
Labels: type: feature, automerge

#4037 chore(tests): update hugo-bin and regenerate lock files
  .gitignore
  tests/eleventy-site/package-lock.json
  tests/hugo-site/package-lock.json
  tests/hugo-site/package.json
Labels: type: chore, automerge

#3970 chore(deps): remove unneeded devDependencies, regenerate lock file
  npm-shrinkwrap.json
  package.json
Labels: type: chore, automerge

#4041 chore: fix Husky
  .github/workflows/benchmark.yml
  npm-shrinkwrap.json
  package.json
Labels: type: chore, automerge

#3899 feat: add context to deploy command
  docs/commands/deploy.md
  src/commands/deploy/deploy.js
Labels: type: feature

#4046 fix: binary not found for Husky
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#4045 chore(ci): stop updating npm
  .github/workflows/pre-release.yml
Labels: type: chore, automerge

#4049 chore: remove `prepack` and `postpack` npm scripts
  package.json
Labels: type: chore, automerge

#4066 chore: fix GitHub action checking for install size
  .github/workflows/benchmark.yml
Labels: type: chore, automerge

#4040 fix(command-build): allow setting context via CONTEXT env, default to production
  src/commands/base-command.js
  tests/command.build.test.js
Labels: type: bug, automerge

#4024 test: add e2e tests for cli
  .eslintrc.js
  .github/workflows/e2e-test.yml
  e2e.config.cjs
  e2e/install.e2e.js
  e2e/utils.js
  npm-shrinkwrap.json
  package.json
  tools/e2e/run.js
  tools/e2e/setup.js
Labels: type: chore, automerge

#4077 chore: fix prerelease step
  .github/workflows/pre-release.yml
Labels: type: chore, automerge

#4076 fix: fixes an issue where the autocomplete could not be written
  src/lib/completion/generate-autocompletion.js
Labels: type: bug

#4084 chore: fixes an issue with the e2e tests
  tools/e2e/run.js
  tools/e2e/setup.js
Labels: type: chore

#4064 fix: live tunnel arch issue
  bin/run
  npm-shrinkwrap.json
  package.json
  src/commands/base-command.js
  src/lib/exec-fetcher.js
  src/lib/exec-fetcher.test.js
  src/utils/command-helpers.js
Labels: type: bug, automerge

#4048 feat(command-dev): add support for functionsPort flag fixes #3980
  docs/commands/dev.md
  src/commands/dev/dev.js
Labels: type: feature, automerge

#4097 feat: pass `zipGo` property to ZISI
  src/lib/functions/config.js
Labels: type: feature, automerge

#4101 test: disable flaky tests on windows
  tests/command.init.test.js
  tests/command.link.test.js
Labels: type: chore

#4102 Disable flaky tests on windows
  tests/command.init.test.js
Labels: type: chore

#4106 feat(dev): document how to disable browser auto launch
  docs/commands/dev.md
  docs/netlify-dev.md
  src/commands/dev/dev.js
Labels: type: feature, automerge

#3904 feat: add Netlify Graph support
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-pull.js
  src/commands/graph/graph.js
  src/commands/graph/index.js
  src/commands/main.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/assets/netlifyGraphOperationsLibrary.graphql
  tests/assets/netlifyGraphSchema.graphql
  tests/command.graph.test.js
  tests/graph-codegen.test.js
  tests/snapshots/command.graph.test.js.md
  tests/snapshots/command.graph.test.js.snap
  tests/snapshots/command.help.test.js.md
  tests/snapshots/command.help.test.js.snap
  tests/snapshots/graph-codegen.test.js.md
  tests/snapshots/graph-codegen.test.js.snap
Labels: type: feature

#3901 feat: automatically link site post creation
  docs/commands/sites.md
  src/commands/link/link.js
  src/commands/sites/sites-create.js
  tests/command.init.test.js
Labels: type: feature, automerge

#4132 fix(command-dev): optionally pass settings to getNetlifyGraphConfig
  src/commands/dev/dev.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4136 chore(site): add graph to nav bar
  site/src/_app.js
Labels: type: chore, automerge

#4142 chore: migrate e2e tests to esm modules
  e2e.config.mjs
  e2e/install.e2e.mjs
  e2e/utils.js
  e2e/utils.mjs
  package.json
  tools/e2e/run.mjs
  tools/e2e/setup.mjs
Labels: type: chore

#3689 feat: add local dev experience for scheduled functions
  npm-shrinkwrap.json
  package.json
  src/commands/functions/functions-invoke.js
  src/lib/functions/netlify-function.js
  src/lib/functions/runtimes/js/builders/zisi.js
  src/lib/functions/runtimes/js/index.js
  src/lib/functions/scheduled.js
  src/lib/functions/scheduled.test.js
  src/lib/functions/server.js
  src/lib/functions/server.test.js
  src/utils/functions/constants.js
  src/utils/functions/get-functions.js
  src/utils/functions/get-functions.test.js
  src/utils/functions/index.js
  tests/command.functions.test.js
Labels: type: feature

#4162 fix: dont show warning message for toml-defined scheduled functions
  src/commands/functions/functions-invoke.js
  src/utils/functions/get-functions.js
  tests/command.functions.test.js
Labels: type: bug
