Repository netlify/cli, pull requests merged in 2022-08, with the labels that each got.

#4879 fix(graph): Harden Graph calls
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-client.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#4871 feat(env): add .local variants to defaultEnvFiles (#1604)
  docs/netlify-dev.md
  src/utils/dot-env.js
  tests/unit/utils/dot-env.test.js
Labels: type: feature, automerge

#4877 docs: update docs site URLs
  README.md
  docs/README.md
  docs/commands/addons.md
  docs/netlify-dev.md
  package.json
  src/commands/functions/functions-invoke.js
  src/commands/main.js
  src/functions-templates/javascript/graphql-gateway/{{name}}.js
  src/functions-templates/javascript/hello-world/{{name}}.js
  src/functions-templates/javascript/identity-signup/{{name}}.js
  src/functions-templates/javascript/serverless-ssr/app/index.js
  src/utils/init/utils.js
Labels: type: chore

#4892 chore: fix vale workflow
  .github/workflows/vale.yml
Labels: type: chore, automerge

#4711 feat: add graph:init command
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-init.js
  src/commands/graph/graph.js
  src/commands/login/login.js
  tests/integration/snapshots/220.command.graph.test.js.md
  tests/integration/snapshots/220.command.graph.test.js.snap
Labels: type: feature, automerge

#4891 chore: fix security issues in some node dependencies
  npm-shrinkwrap.json
Labels: type: chore, automerge

#4899 feat(graph): allow sharing VCS branches through a lockfile
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-init.js
  src/commands/graph/graph-library.js
  src/commands/graph/graph-pull.js
  src/lib/one-graph/cli-client.js
  tests/integration/snapshots/220.command.graph.test.js.md
  tests/integration/snapshots/220.command.graph.test.js.snap
Labels: type: feature, automerge

#4902 fix: deduplicate shrinkwrap
  npm-shrinkwrap.json
Labels: type: bug, automerge

#4896 feat(graph): open-ended codegen
  docs/commands/graph.md
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-handler.js
  src/commands/graph/graph-init.js
  src/commands/graph/graph-library.js
  src/commands/graph/graph-operations.js
  src/commands/graph/graph-pull.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/530.graph-codegen.test.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: feature, automerge

#4912 feat(graph): handle auto configure codegen module
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: feature, automerge

#4916 fix(graph): update CLI event types
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4918 chore: print stdout/stderr when dev server fails in tests
  tests/integration/600.framework-detection.test.js
  tests/integration/utils/dev-server.js
Labels: type: chore, automerge

#4919 fix: Update edge-bundler and ensure only allowed environment variables are supplied to edge functions
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/edge-functions/proxy.js
  src/lib/edge-functions/registry.js
  src/utils/proxy.js
  tests/integration/100.command.dev.test.js
Labels: type: bug, automerge

#4922 fix: update graph dep to handle unions and interfaces
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: bug, automerge

#4910 chore: correct step 2 of git setup instructions
  src/commands/init/init.js
Labels: type: chore, area: command: init, automerge

#4839 feat: read scopes and contexts in `env:get`, `env:list`, and `dev`
  docs/commands/dev.md
  docs/commands/env.md
  src/commands/dev/dev.js
  src/commands/env/env-get.js
  src/commands/env/env-list.js
  src/utils/dev.js
  src/utils/env/index.js
  tests/integration/400.command.dev.test.js
  tests/integration/610.command.env.test.js
  tests/integration/650.command.envelope.test.js
  tests/integration/snapshots/610.command.env.test.js.md
  tests/integration/snapshots/610.command.env.test.js.snap
  tests/integration/utils/dev-server.js
  tests/unit/utils/env/index.test.js
Labels: type: feature, automerge

#4925 fix(graph): Support fragments on interfaces during codegen
  npm-shrinkwrap.json
  package.json
  tests/integration/530.graph-codegen.test.js
Labels: type: bug, automerge

#4926 fix(graph): update graph dep
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#4937 fix(graph): bump codegen dep to handle solely named fragments on union
  npm-shrinkwrap.json
  package.json
Labels: type: bug, automerge

#4938 fix(graph): use jwt when persisted operation doc
  src/commands/graph/graph-edit.js
Labels: type: bug, automerge

#4897 fix: stop pass through request params for function redirects
  src/utils/proxy.js
  tests/integration/200.command.dev.test.js
Labels: type: bug, automerge

#4553 fix: report an error whe running site:create nameflag is invalid
  src/commands/sites/sites-create.js
  tests/integration/140.command.sites.test.js
Labels: type: bug, area: command: sites, automerge

#4950 fix(graph): support fragments and passing data to handler generation
  docs/commands/graph.md
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-handler.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4951 fix(graph): don't attach codegen to session metadata, and don't die when missing toml config
  npm-shrinkwrap.json
  package.json
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4947 chore: support envelope in graph:init
  src/commands/graph/graph-init.js
  tests/integration/220.command.graph.test.js
Labels: type: chore, automerge

#4953 fix: avoid bright chalk colors in env commands, fix logging typo
  src/commands/env/env-clone.js
  src/commands/env/env-get.js
  src/commands/env/env-list.js
Labels: type: bug, automerge

#4959 fix(graph): publish codegen module metadata for Graph ui
  src/lib/one-graph/cli-client.js
Labels: type: bug, automerge

#4944 chore: run all unit tests in ci and fix for node 12
  package.json
  tests/unit/utils/functions/registry.test.js
Labels: type: chore, automerge

#4967 fix: supply NETLIFY_DEV to Deno
  src/lib/edge-functions/registry.js
  tests/integration/100.command.dev.test.js
Labels: type: bug

#4929 fix: fix local builds with plugins and build settings from the ui
  src/lib/build.js
  tests/integration/110.command.build.test.js
  tests/integration/utils/site-builder.js
Labels: type: bug, automerge

#4949 feat: support env context in `dev:exec` and `build`
  docs/commands/build.md
  docs/commands/dev.md
  src/commands/build/build.js
  src/commands/dev/dev-exec.js
  src/commands/dev/dev.js
Labels: type: feature, automerge

#4966 feat: support scopes and contexts in `env:set` and `env:unset`
  docs/commands/env.md
  src/commands/env/env-import.js
  src/commands/env/env-list.js
  src/commands/env/env-set.js
  src/commands/env/env-unset.js
  src/utils/env/index.js
  tests/integration/650.command.envelope.test.js
Labels: type: feature, automerge

#4968 fix(ci): do not build site during prerelease workflow
  .github/workflows/pre-release.yml
Labels: type: bug, automerge

#4969 fix: incorrect destructuring in `netlify build`
  src/commands/build/build.js
Labels: type: bug, automerge, echoes/initiative: americas/secret-management

#4964 feat: run plugins in Netlify Dev
  src/commands/dev/dev.js
  src/utils/detect-server-settings.js
  src/utils/types.d.ts
  tests/integration/500.command.dev.test.js
  tests/integration/600.framework-detection.test.js
  tests/integration/snapshots/600.framework-detection.test.js.md
  tests/integration/snapshots/600.framework-detection.test.js.snap
  tests/integration/utils/snapshots.js
Labels: type: feature

#4975 feat: add `.netlify` to `.gitignore` in Netlify Dev
  src/commands/dev/dev.js
  tests/integration/0.command.dev.test.js
Labels: type: feature

#4979 feat: simplify `init` and `link` flows
  src/commands/init/init.js
  src/commands/link/link.js
  src/commands/sites/sites-create.js
  src/utils/init/config-github.js
  src/utils/init/plugins.js
  src/utils/init/utils.js
  tests/integration/420.command.init.test.js
Labels: type: feature, automerge

#4976 chore: add expresion to snapshot normaliser
  tests/integration/snapshots/600.framework-detection.test.js.md
  tests/integration/snapshots/600.framework-detection.test.js.snap
  tests/integration/utils/snapshots.js
Labels: type: chore, automerge

#4984 fix(graph): make handler generation async/effectful
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
Labels: type: bug, automerge

#4978 feat: allow multiple operation names in graph:hander
  docs/commands/graph.md
  src/commands/graph/graph-handler.js
Labels: type: feature, automerge

#4791 chore: enable the use eszip feature flag for edge functions
  src/commands/deploy/deploy.js
  src/lib/build.js
Labels: type: feature

#4977 feat: support branch values for environment variable contexts
  docs/commands/build.md
  docs/commands/dev.md
  docs/commands/env.md
  package.json
  src/commands/build/build.js
  src/commands/dev/dev-exec.js
  src/commands/dev/dev.js
  src/commands/env/env-get.js
  src/commands/env/env-list.js
  src/commands/env/env-set.js
  src/commands/env/env-unset.js
  src/utils/env/index.js
  tests/unit/utils/env/index.test.js
Labels: type: feature, automerge

#5005 fix: correctly allow redirects to external URLs
  src/utils/proxy.js
  tests/integration/0.command.dev.test.js
  tests/integration/400.command.dev.test.js
  tests/integration/500.command.dev.test.js
Labels: type: bug, automerge

#5017 chore: add instructions on how to see stack traces
  CONTRIBUTING.md
Labels: type: chore, automerge
