Repository netlify/cli, pull requests merged in 2022-06, with the labels that each got.

#4658 fix: fix scheduled function template to use async
  src/functions-templates/typescript/scheduled-function/{{name}}.ts
Labels: type: bug, area: functions, automerge

#4660 chore: remove Go scheduled functions template
  src/functions-templates/go/scheduled-function/.netlify-function-template.js
  src/functions-templates/go/scheduled-function/go.mod
  src/functions-templates/go/scheduled-function/go.sum
  src/functions-templates/go/scheduled-function/netlify.toml
  src/functions-templates/go/scheduled-function/src/hourly-schedule/main.go
Labels: type: chore, automerge

#4619 fix: correctly watch function files specified in the config option `included_files`
  src/lib/functions/netlify-function.js
  src/lib/functions/registry.js
  src/lib/functions/runtimes/js/builders/zisi.js
  tests/integration/330.serving-functions.test.js
  tests/unit/utils/functions/registry.test.js
Labels: type: bug, area: functions, automerge

#4681 feat: add client ip header to edge func local dev
  src/lib/edge-functions/headers.js
  src/lib/edge-functions/proxy.js
Labels: type: feature

#4680 chore: fix codeql scanning
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: type: chore, area: ci, automerge

#4683 feat: show progress while waiting for framework server to start
  package.json
  src/commands/dev/dev.js
  tests/integration/600.framework-detection.test.js
  tests/integration/snapshots/600.framework-detection.test.js.md
  tests/integration/snapshots/600.framework-detection.test.js.snap
Labels: type: feature, automerge

#4532 chore(docs): add information on netlify-dev and tests
  CONTRIBUTING.md
Labels: type: chore, automerge

#4699 feat: Allow user to configure an editor to open file for Graph
  npm-shrinkwrap.json
  package.json
  src/commands/graph/graph-pull.js
  src/lib/one-graph/cli-client.js
  src/lib/one-graph/cli-netlify-graph.js
  tests/integration/530.graph-codegen.test.js
  tests/integration/snapshots/530.graph-codegen.test.js.md
  tests/integration/snapshots/530.graph-codegen.test.js.snap
Labels: type: feature, automerge

#4698 feat: check for deno vs code ext and download when prompted
  src/recipes/vscode/index.js
Labels: type: chore, type: feature, type: bug

#4685 fix: gracefully fail Edge Functions in case of deno binary issues
  src/lib/edge-functions/proxy.js
Labels: type: bug

#4710 fix: Update graph edit
  src/commands/graph/graph-edit.js
  src/commands/graph/graph-operations.js
  src/commands/graph/graph.js
  src/lib/one-graph/cli-client.js
Labels: type: bug, automerge
