Repository netlify/cli, pull requests merged in 2022-12, with the labels that each got.

#5290 fix: detect requests without body correctly
  src/lib/functions/server.mjs
  tests/integration/400.command.dev.test.cjs
Labels: automerge

#5269 chore: introduce vitests for tests
  .eslintrc.cjs
  .github/workflows/e2e-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/legacy-tests.yml
  .github/workflows/unit-tests.yml
  e2e.config.mjs
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.mjs
  src/functions-templates/javascript/graphql-gateway/example-sibling-function-graphql-1.js
  src/functions-templates/javascript/graphql-gateway/example-sibling-function-graphql-2.js
  src/lib/edge-functions/consts.cjs
  src/utils/command-helpers.cjs
  tests/integration/530.graph-codegen.test.mjs
  tests/integration/__snapshots__/530.graph-codegen.test.mjs.snap
  tests/integration/snapshots/530.graph-codegen.test.mjs.md
  tests/integration/snapshots/530.graph-codegen.test.mjs.snap
  tests/integration/utils/got.cjs
  tests/unit/lib/completion/__snapshots__/generate-autocompletion.test.mjs.snap
  tests/unit/lib/completion/generate-autocompletion.test.mjs
  tests/unit/lib/completion/get-autocompletion.test.mjs
  tests/unit/lib/completion/snapshots/completion.test.cjs.md
  tests/unit/lib/completion/snapshots/completion.test.cjs.snap
  tests/unit/lib/completion/snapshots/generate-autocompletion.test.mjs.md
  tests/unit/lib/completion/snapshots/generate-autocompletion.test.mjs.snap
  tests/unit/lib/functions/scheduled.test.mjs
  tests/unit/lib/functions/server.test.cjs
  tests/unit/lib/http-agent.test.mjs
  tests/unit/utils/functions/get-functions.test.mjs
  tests/unit/utils/gh-auth.test.cjs
  tests/unit/utils/read-repo-url.test.mjs
  tests/unit/utils/telemetry/validation.test.mjs
  tools/affected-test.mjs
  vitest.config.mjs
Labels: automerge

#5299 fix: discard edge function declarations without a path or pattern
  src/lib/edge-functions/registry.cjs
Labels: type: bug, automerge

#5302 fix: always look for internal edge functions
  src/lib/edge-functions/internal.cjs
  tests/integration/100.command.dev.test.cjs
Labels: type: bug

#5311 fix: allow for in-source-config internal edge functions in proxy
  src/lib/edge-functions/internal.mjs
  src/lib/edge-functions/proxy.mjs
  tests/integration/100.command.dev.test.cjs
Labels: type: bug

#5315 feat: load edge function import maps from Deno config file
  src/commands/deploy/deploy.mjs
  src/lib/edge-functions/proxy.mjs
  tests/integration/100.command.dev.test.cjs
Labels: type: feature

#5316 fix: centralize edge functions feature flags
  src/commands/deploy/deploy.mjs
  src/lib/build.mjs
  src/lib/edge-functions/consts.mjs
Labels: type: bug, automerge

#5322 feat(command-env): add support for plaintext output in env:list
  docs/commands/env.md
  src/commands/env/env-list.mjs
Labels: type: feature, automerge, area: command: env
