Repository netlify/cli, pull requests merged in 2023-04, with the labels that each got.

#5607 fix(live): make LIVE_URL env var available in --live mode
  src/commands/dev/dev.mjs
  src/utils/proxy.mjs
  src/utils/run-build.mjs
Labels: type: bug, low-risk

#5617 fix: determine duplicate function precedence based on extension
  src/lib/functions/registry.mjs
  tests/unit/lib/functions/registry.test.mjs
Labels: type: bug, automerge

#5622 fix: revert 8ae14561c600c86f3a69657eb641ac5431419d88
  src/lib/functions/registry.mjs
  tests/unit/lib/functions/registry.test.mjs
Labels: type: bug

#5623 fix: determine duplicate function precedence based on extension
  src/lib/functions/registry.mjs
  src/lib/functions/server.mjs
  tests/unit/lib/functions/registry.test.mjs
Labels: type: feature

#5484 chore: use TS for tests and move all mjs tests into new structure
  .eslintrc.cjs
  .github/workflows/integration-tests.yml
  .github/workflows/legacy-tests.yml
  npm-shrinkwrap.json
  package.json
  tests/integration/120.command.status.test.cjs
  tests/integration/30.command.lm.test.mjs
  tests/integration/520.command.link.test.mjs
  tests/integration/__fixtures__/dev-server-with-functions/functions/scheduled-isc-body.js
  tests/integration/__fixtures__/dev-server-with-functions/functions/scheduled-isc.js
  tests/integration/__fixtures__/empty-project/.gitkeep
  tests/integration/__snapshots__/graph-codegen.test.ts.snap
  tests/integration/commands/dev/functions.test.mjs
  tests/integration/commands/dev/functions.test.ts
  tests/integration/commands/functions-create/functions-create.test.ts
  tests/integration/commands/functions-invoke/functions-invoke.test.mjs
  tests/integration/commands/functions-invoke/functions-invoke.test.ts
  tests/integration/commands/help/__snapshots__/help.test.ts.snap
  tests/integration/commands/help/help.test.ts
  tests/integration/commands/link/link.test.ts
  tests/integration/commands/lm/lm.test.ts
  tests/integration/commands/sites/sites.test.ts
  tests/integration/commands/status/__snapshots__/status.test.ts.snap
  tests/integration/commands/status/status.test.ts
  tests/integration/frameworks/hugo.test.mjs
  tests/integration/frameworks/hugo.test.ts
  tests/integration/graph-codegen.test.ts
  tests/integration/rules-proxy.test.ts
  tests/integration/utils/call-cli.cjs
  tests/integration/utils/fixture.mjs
  tests/integration/utils/fixture.ts
  tests/integration/utils/mock-api.cjs
  tests/integration/utils/site-builder.cjs
  tsconfig.json
  vitest.config.ts
Labels: automerge

#5629 chore: fix handle-questions helper to support autocomplete
  tests/integration/600.framework-detection.test.cjs
  tests/integration/640.command.recipes.test.cjs
  tests/integration/commands/functions-create/functions-create.test.ts
  tests/integration/utils/handle-questions.cjs
Labels: automerge

#5656 feat: add npm provenance
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  package.json
Labels: type: feature
