Repository netlify/cli, pull requests merged in 2023-03, with the labels that each got.

#5517 docs: add links to compliance content in the footer
  site/src/_layout.js
Labels: area: docs, automerge

#5522 test: fix snapshots that contain graph commands due to deprecation
  tests/integration/snapshots/220.command.graph.test.cjs.md
  tests/integration/snapshots/220.command.graph.test.cjs.snap
  tests/integration/snapshots/320.command.help.test.cjs.md
  tests/integration/snapshots/320.command.help.test.cjs.snap
Labels: type: chore

#5524 fix: graph deprecation snapshots with normalization
  tests/integration/utils/snapshots.cjs
Labels: type: chore, automerge

#5493 feat: remove ff project_deploy_configuration_api_use_per_function_configuration_files
  src/lib/build.mjs
  src/lib/functions/registry.mjs
  src/utils/deploy/hash-fns.mjs
Labels: type: chore

#5538 fix: wrong env values could be used for non-dev context in `netlify deploy --build --context`
  src/commands/deploy/deploy.mjs
  src/utils/env/index.mjs
Labels: automerge

#5564 fix: update edge functions bootstrap to `641064c685071e00083eb682`
  src/lib/edge-functions/bootstrap.mjs
Labels: automerge

#5577 chore: add unit test for getPackageJson
  tests/unit/utils/get-package-json.test.mjs
Labels: automerge

#5582 chore: improve on getPackageJson tests
  tests/unit/utils/get-package-json.test.mjs
Labels: automerge

#5599 feat: add tag inside the head element
  site/src/_layout.js
Labels: area: docs
