Repository netlify/cli, pull requests merged in 2023-09, with the labels that each got.

#5975 chore: deprecate `lm` command
  README.md
  docs/README.md
  docs/commands/index.md
  docs/commands/lm.md
  site/src/_app.js
  src/commands/lm/lm-info.mjs
  src/commands/lm/lm-install.mjs
  src/commands/lm/lm-setup.mjs
  src/commands/lm/lm.mjs
  tests/integration/commands/help/__snapshots__/help.test.ts.snap
Labels: area: command: lm

#5930 refactor: tests/integration/640.command.recipes.test.cjs
  tests/integration/640.command.recipes.test.cjs
  tests/integration/commands/recipes/__snapshots__/recipes.test.mjs.snap
  tests/integration/commands/recipes/recipes.test.mjs
  tests/integration/snapshots/640.command.recipes.test.cjs.md
  tests/integration/snapshots/640.command.recipes.test.cjs.snap
Labels: automerge

#5924 refactor: tests/integration/500.command.dev.test.cjs
  tests/integration/500.command.dev.test.cjs
  tests/integration/commands/dev/dev-forms-and-redirects.test.mjs
Labels: automerge

#5920 refactor: tests/integration/300.command.dev.test.cjs
  tests/integration/300.command.dev.test.cjs
  tests/integration/commands/dev/responses.dev.test.mjs
Labels: automerge

#5925 refactor: tests/integration/610.command.env.test.cjs
  tests/integration/610.command.env.test.cjs
  tests/integration/commands/env/__snapshots__/env.test.mjs.snap
  tests/integration/commands/env/env.test.mjs
  tests/integration/snapshots/610.command.env.test.cjs.md
  tests/integration/snapshots/610.command.env.test.cjs.snap
Labels: automerge

#6001 fix: fixes an issue where the provided --dir flag was not used
  src/commands/deploy/deploy.mjs
Labels: Ecosystem: Dev Foundations

#5996 fix: pass feature flags from siteInfo for build
  src/lib/build.mjs
Labels: automerge
