Repository netlify/cli, pull requests merged in 2023-01, with the labels that each got.

#5340 feat: use console.log for logging in ef template
  src/functions-templates/typescript/log/{{name}}.ts
Labels: automerge

#5342 feat(ef templates): replace context.json with Response.json
  src/functions-templates/typescript/geolocation/{{name}}.ts
  src/functions-templates/typescript/json/{{name}}.ts
Labels: type: feature, automerge

#5341 fix(command-dev): replace deprecated static-server dep by fastify-static
  npm-shrinkwrap.json
  package.json
  src/commands/dev/dev.mjs
  tests/integration/100.command.dev.test.cjs
  tests/integration/500.command.dev.test.cjs
Labels: type: security, area: command: dev, automerge

#5344 chore: remove contributors from package.json and rely on the GitHub UI
  .github/workflows/contributors.yml
  package.json
  site/package.json
Labels: automerge

#5337 docs: add help, update docs for env:list --json flag
  docs/commands/env.md
  src/commands/env/env-list.mjs
Labels: type: bug, area: docs, automerge

#5338 feat: add `--prod` flag to `dev` command
  .eslintrc.cjs
  docs/commands/dev.md
  npm-shrinkwrap.json
  package.json
  src/commands/base-command.mjs
  src/commands/dev/dev.mjs
  src/commands/functions/functions-serve.mjs
  src/lib/edge-functions/registry.mjs
  src/lib/functions/registry.mjs
  src/lib/functions/runtimes/js/builders/zisi.mjs
  src/lib/functions/runtimes/rust/index.mjs
  src/lib/functions/server.mjs
  src/utils/dev.mjs
  src/utils/functions/functions.mjs
  tests/integration/100.command.dev.test.cjs
  tests/integration/20.command.functions.test.cjs
  tests/integration/200.command.dev.test.cjs
  tests/integration/210.command.deploy.test.cjs
  tests/integration/300.command.dev.test.cjs
  tests/integration/330.serving-functions.test.cjs
  tests/integration/400.command.dev.test.cjs
  tests/integration/500.command.dev.test.cjs
  tests/integration/600.framework-detection.test.cjs
  tests/integration/commands/functions-invoke/functions-invoke.test.mjs
  tests/integration/eleventy-site/functions/echo.cjs
  tests/integration/snapshots/600.framework-detection.test.cjs.md
  tests/integration/snapshots/600.framework-detection.test.cjs.snap
  tests/integration/utils/dev-server.cjs
  tests/unit/utils/deploy/hash-fns.test.mjs
Labels: type: feature

#5335 chore: add retry to CI workflows
  .github/workflows/integration-tests.yml
  .github/workflows/legacy-tests.yml
  .github/workflows/unit-tests.yml
Labels: type: chore, automerge

#5360 chore: update test snapshot
  tests/integration/snapshots/320.command.help.test.cjs.md
  tests/integration/snapshots/320.command.help.test.cjs.snap
Labels: type: chore, automerge

#5359 fix: publish shrinkwrap with prod dependencies only
  .github/workflows/benchmark.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/legacy-tests.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify-docs.yml
  .npmrc
  package-lock.json
  package.json
  tools/affected-test.mjs
  tools/tests/affected-files.test.mjs
  tools/tests/utils/file-systems.mjs
Labels: automerge

#5366 feat: support ef excluded patterns
  src/lib/edge-functions/registry.mjs
  tests/integration/100.command.dev.test.cjs
Labels: type: feature, automerge

#5371 chore: use esm config for renovate
  renovate.json5
Labels: automerge

#5404 test: update snapshots after merging flag case changes
  tests/integration/snapshots/220.command.graph.test.cjs.md
  tests/integration/snapshots/220.command.graph.test.cjs.snap
  tests/integration/snapshots/320.command.help.test.cjs.md
  tests/integration/snapshots/320.command.help.test.cjs.snap
Labels: type: chore, automerge

#5409 fix: ensure edge functions work with HTTPS mode
  src/lib/edge-functions/headers.mjs
  src/lib/edge-functions/proxy.mjs
  src/utils/proxy.mjs
Labels: type: bug

#5411 fix: gracefully handle errors when setting headers
  src/lib/functions/server.mjs
  src/lib/functions/synchronous.mjs
Labels: type: bug, automerge

#5414 feat: add support for signed redirects
  src/utils/proxy.mjs
  src/utils/redirects.mjs
  src/utils/sign-redirect.mjs
  tests/integration/0.command.dev.test.cjs
  tests/integration/utils/external-server.cjs
Labels: type: feature

#5415 fix: sign redirect with secret from env var
  src/utils/proxy.mjs
  tests/integration/0.command.dev.test.cjs
Labels: type: bug

#5429 fix: load internal environment variables in Envelope
  src/utils/env/index.mjs
  tests/integration/100.command.dev.test.cjs
  tests/integration/utils/external-server-cli.cjs
  tests/integration/utils/external-server.cjs
Labels: type: bug

#5437 fix: update got & remove outdated workaround
  npm-shrinkwrap.json
  package.json
  tests/integration/utils/got.cjs
Labels: type: security, automerge
