Repository netlify/cli, pull requests merged in 2023-02, with the labels that each got.

#5447 fix: print deploy error_message, if exists
  src/utils/deploy/util.mjs
Labels: type: bug, automerge

#5450 chore(deps): update node-version-alias to v2.0.0
  npm-shrinkwrap.json
  package.json
Labels: dependencies, type: security, automerge

#5436 feat: support comments in vscode settings
  npm-shrinkwrap.json
  package.json
  src/recipes/vscode/settings.mjs
  tests/integration/640.command.recipes.test.cjs
  tests/integration/utils/handle-questions.cjs
Labels: type: feature, automerge

#5461 chore: new fixtures and new setup for dev-server tests
  .eslintignore
  .gitignore
  npm-shrinkwrap.json
  package.json
  tests/integration/__fixtures__/dev-server-with-functions/functions/identity-validate-background.js
  tests/integration/__fixtures__/dev-server-with-functions/functions/ping.js
  tests/integration/__fixtures__/dev-server-with-functions/functions/scheduled-isc.js
  tests/integration/__fixtures__/dev-server-with-functions/functions/scheduled.js
  tests/integration/__fixtures__/dev-server-with-functions/netlify.toml
  tests/integration/__fixtures__/dev-server-with-functions/node_modules/@netlify/functions/index.js
  tests/integration/__fixtures__/dev-server-with-functions/node_modules/@netlify/functions/package.json
  tests/integration/commands/functions-invoke/functions-invoke.test.mjs
  tests/integration/utils/call-cli.cjs
  tests/integration/utils/fixture.mjs
Labels: automerge

#5480 fix: support multiple path values in edge functions config
  src/lib/edge-functions/registry.mjs
  tests/integration/100.command.dev.test.cjs
Labels: automerge

#5483 feat: add generator to functions config on deploy
  src/utils/deploy/hash-fns.mjs
Labels: type: feature

#5487 feat: show displayName for any edge function that has one being run with netlify dev
  src/lib/edge-functions/registry.mjs
Labels: type: feature

#5189 fix(deps): update dependency shell-quote to 1.7.3
  npm-shrinkwrap.json
  site/package-lock.json
Labels: type: bug

#5448 chore: deprecate `graph` command
  README.md
  docs/README.md
  docs/commands/graph.md
  docs/commands/index.md
  src/commands/graph/graph.mjs
Labels: automerge
